#!/bin/bash
rm -v /usr/share/info/bash.info
rm -v /usr/share/man/man1/bash.1
rm -v /usr/share/man/man1/bashbug.1
rm -rf -v /usr/share/doc/bash-4.2
rm -v /usr/share/locale/en@quot/LC_MESSAGES/bash.mo
rm -v /usr/share/locale/ja/LC_MESSAGES/bash.mo
rm -v /usr/share/locale/uk/LC_MESSAGES/bash.mo
rm -v /usr/share/locale/ro/LC_MESSAGES/bash.mo
rm -v /usr/share/locale/ru/LC_MESSAGES/bash.mo
rm -v /usr/share/locale/es/LC_MESSAGES/bash.mo
rm -v /usr/share/locale/sv/LC_MESSAGES/bash.mo
rm -v /usr/share/locale/nl/LC_MESSAGES/bash.mo
rm -v /usr/share/locale/vi/LC_MESSAGES/bash.mo
rm -v /usr/share/locale/et/LC_MESSAGES/bash.mo
rm -v /usr/share/locale/ca/LC_MESSAGES/bash.mo
rm -v /usr/share/locale/tr/LC_MESSAGES/bash.mo
rm -v /usr/share/locale/af/LC_MESSAGES/bash.mo
rm -v /usr/share/locale/eo/LC_MESSAGES/bash.mo
rm -v /usr/share/locale/sk/LC_MESSAGES/bash.mo
rm -v /usr/share/locale/pl/LC_MESSAGES/bash.mo
rm -v /usr/share/locale/ga/LC_MESSAGES/bash.mo
rm -v /usr/share/locale/en@boldquot/LC_MESSAGES/bash.mo
rm -v /usr/share/locale/zh_TW/LC_MESSAGES/bash.mo
rm -v /usr/share/locale/hu/LC_MESSAGES/bash.mo
rm -v /usr/share/locale/bg/LC_MESSAGES/bash.mo
rm -v /usr/share/locale/fi/LC_MESSAGES/bash.mo
rm -v /usr/share/locale/de/LC_MESSAGES/bash.mo
rm -v /usr/share/locale/pt_BR/LC_MESSAGES/bash.mo
rm -v /usr/share/locale/id/LC_MESSAGES/bash.mo
rm -v /usr/share/locale/zh_CN/LC_MESSAGES/bash.mo
rm -v /usr/share/locale/cs/LC_MESSAGES/bash.mo
rm -v /usr/share/locale/fr/LC_MESSAGES/bash.mo
rm -v /usr/share/locale/lt/LC_MESSAGES/bash.mo
rm -v /bin/bash
rm -v /bin/bashbug
