#!/bin/bash
rm -v /usr/bin/yacc
rm -v /usr/bin/bison
rm -v /usr/share/info/bison.info
rm -v /usr/share/man/man1/yacc.1
rm -v /usr/share/man/man1/bison.1
rm -v /usr/share/aclocal/bison-i18n.m4
rm -rf -v /usr/share/bison
rm -v /usr/share/locale/ja/LC_MESSAGES/bison-runtime.mo
rm -v /usr/share/locale/ja/LC_MESSAGES/bison.mo
rm -v /usr/share/locale/uk/LC_MESSAGES/bison-runtime.mo
rm -v /usr/share/locale/uk/LC_MESSAGES/bison.mo
rm -v /usr/share/locale/ro/LC_MESSAGES/bison-runtime.mo
rm -v /usr/share/locale/ro/LC_MESSAGES/bison.mo
rm -v /usr/share/locale/ru/LC_MESSAGES/bison-runtime.mo
rm -v /usr/share/locale/ru/LC_MESSAGES/bison.mo
rm -v /usr/share/locale/th/LC_MESSAGES/bison-runtime.mo
rm -v /usr/share/locale/es/LC_MESSAGES/bison-runtime.mo
rm -v /usr/share/locale/es/LC_MESSAGES/bison.mo
rm -v /usr/share/locale/sv/LC_MESSAGES/bison-runtime.mo
rm -v /usr/share/locale/sv/LC_MESSAGES/bison.mo
rm -v /usr/share/locale/nl/LC_MESSAGES/bison-runtime.mo
rm -v /usr/share/locale/nl/LC_MESSAGES/bison.mo
rm -v /usr/share/locale/nb/LC_MESSAGES/bison-runtime.mo
rm -v /usr/share/locale/nb/LC_MESSAGES/bison.mo
rm -v /usr/share/locale/vi/LC_MESSAGES/bison-runtime.mo
rm -v /usr/share/locale/vi/LC_MESSAGES/bison.mo
rm -v /usr/share/locale/hr/LC_MESSAGES/bison-runtime.mo
rm -v /usr/share/locale/hr/LC_MESSAGES/bison.mo
rm -v /usr/share/locale/et/LC_MESSAGES/bison-runtime.mo
rm -v /usr/share/locale/et/LC_MESSAGES/bison.mo
rm -v /usr/share/locale/tr/LC_MESSAGES/bison-runtime.mo
rm -v /usr/share/locale/tr/LC_MESSAGES/bison.mo
rm -v /usr/share/locale/it/LC_MESSAGES/bison-runtime.mo
rm -v /usr/share/locale/it/LC_MESSAGES/bison.mo
rm -v /usr/share/locale/pl/LC_MESSAGES/bison-runtime.mo
rm -v /usr/share/locale/pl/LC_MESSAGES/bison.mo
rm -v /usr/share/locale/ky/LC_MESSAGES/bison-runtime.mo
rm -v /usr/share/locale/ga/LC_MESSAGES/bison-runtime.mo
rm -v /usr/share/locale/ga/LC_MESSAGES/bison.mo
rm -v /usr/share/locale/el/LC_MESSAGES/bison-runtime.mo
rm -v /usr/share/locale/el/LC_MESSAGES/bison.mo
rm -v /usr/share/locale/zh_TW/LC_MESSAGES/bison-runtime.mo
rm -v /usr/share/locale/zh_TW/LC_MESSAGES/bison.mo
rm -v /usr/share/locale/fi/LC_MESSAGES/bison-runtime.mo
rm -v /usr/share/locale/fi/LC_MESSAGES/bison.mo
rm -v /usr/share/locale/de/LC_MESSAGES/bison-runtime.mo
rm -v /usr/share/locale/de/LC_MESSAGES/bison.mo
rm -v /usr/share/locale/pt_BR/LC_MESSAGES/bison-runtime.mo
rm -v /usr/share/locale/pt_BR/LC_MESSAGES/bison.mo
rm -v /usr/share/locale/id/LC_MESSAGES/bison-runtime.mo
rm -v /usr/share/locale/id/LC_MESSAGES/bison.mo
rm -v /usr/share/locale/zh_CN/LC_MESSAGES/bison-runtime.mo
rm -v /usr/share/locale/pt/LC_MESSAGES/bison-runtime.mo
rm -v /usr/share/locale/pt/LC_MESSAGES/bison.mo
rm -v /usr/share/locale/sl/LC_MESSAGES/bison-runtime.mo
rm -v /usr/share/locale/ast/LC_MESSAGES/bison-runtime.mo
rm -v /usr/share/locale/fr/LC_MESSAGES/bison-runtime.mo
rm -v /usr/share/locale/fr/LC_MESSAGES/bison.mo
rm -v /usr/share/locale/lv/LC_MESSAGES/bison-runtime.mo
rm -v /usr/share/locale/lt/LC_MESSAGES/bison-runtime.mo
rm -v /usr/share/locale/da/LC_MESSAGES/bison-runtime.mo
rm -v /usr/share/locale/da/LC_MESSAGES/bison.mo
rm -v /usr/share/locale/ms/LC_MESSAGES/bison-runtime.mo
rm -v /usr/share/locale/ms/LC_MESSAGES/bison.mo
rm -v /usr/lib/liby.a
