#!/bin/bash
rm -v /usr/bin/false
rm -v /usr/bin/pathchk
rm -v /usr/bin/pwd
rm -v /usr/bin/nproc
rm -v /usr/bin/du
rm -v /usr/bin/tail
rm -v /usr/bin/cut
rm -v /usr/bin/od
rm -v /usr/bin/wc
rm -v /usr/bin/sync
rm -v /usr/bin/sha1sum
rm -v /usr/bin/sha384sum
rm -v /usr/bin/factor
rm -v /usr/bin/install
rm -v /usr/bin/sha224sum
rm -v /usr/bin/readlink
rm -v /usr/bin/rm
rm -v /usr/bin/sum
rm -v /usr/bin/chmod
rm -v /usr/bin/pr
rm -v /usr/bin/nl
rm -v /usr/bin/basename
rm -v /usr/bin/groups
rm -v /usr/bin/dircolors
rm -v /usr/bin/dir
rm -v /usr/bin/unlink
rm -v /usr/bin/paste
rm -v /usr/bin/logname
rm -v /usr/bin/dirname
rm -v /usr/bin/chown
rm -v /usr/bin/mv
rm -v /usr/bin/tr
rm -v /usr/bin/sort
rm -v /usr/bin/cksum
rm -v /usr/bin/stdbuf
rm -v /usr/bin/uname
rm -v /usr/bin/dd
rm -v /usr/bin/test
rm -v /usr/bin/head
rm -v /usr/bin/vdir
rm -v /usr/bin/truncate
rm -v /usr/bin/mkfifo
rm -v /usr/bin/uniq
rm -v /usr/bin/expr
rm -v /usr/bin/date
rm -v /usr/bin/hostid
rm -v /usr/bin/link
rm -v /usr/bin/csplit
rm -v /usr/bin/nohup
rm -v /usr/bin/tty
rm -v /usr/bin/tee
rm -v /usr/bin/printenv
rm -v /usr/bin/sha512sum
rm -v /usr/bin/rmdir
rm -v /usr/bin/runcon
rm -v /usr/bin/stty
rm -v /usr/bin/seq
rm -v /usr/bin/mknod
rm -v /usr/bin/shuf
rm -v /usr/bin/whoami
rm -v /usr/bin/expand
rm -v /usr/bin/touch
rm -v /usr/bin/base64
rm -v /usr/bin/mktemp
rm -v /usr/bin/fmt
rm -v /usr/bin/ln
rm -v /usr/bin/tac
rm -v /usr/bin/id
rm -v /usr/bin/true
rm -v /usr/bin/sha256sum
rm -v /usr/bin/cat
rm -v /usr/bin/shred
rm -v /usr/bin/sleep
rm -v /usr/bin/pinky
rm -v /usr/bin/ptx
rm -v /usr/bin/nice
rm -v /usr/bin/cp
rm -v /usr/bin/md5sum
rm -v /usr/bin/echo
rm -v /usr/bin/timeout
rm -v /usr/bin/comm
rm -v /usr/bin/ls
rm -v /usr/bin/split
rm -v /usr/bin/unexpand
rm -v /usr/bin/stat
rm -v /usr/bin/users
rm -v /usr/bin/mkdir
rm -v /usr/bin/[
rm -v /usr/bin/chroot
rm -v /usr/bin/tsort
rm -v /usr/bin/printf
rm -v /usr/bin/yes
rm -v /usr/bin/df
rm -v /usr/bin/join
rm -v /usr/bin/env
rm -v /usr/bin/chcon
rm -v /usr/bin/fold
rm -v /usr/bin/chgrp
rm -v /usr/bin/who
rm -v /usr/share/info/coreutils.info
rm -v /usr/share/man/man1/sha512sum.1
rm -v /usr/share/man/man1/sleep.1
rm -v /usr/share/man/man1/tr.1
rm -v /usr/share/man/man1/mkdir.1
rm -v /usr/share/man/man1/ln.1
rm -v /usr/share/man/man1/sync.1
rm -v /usr/share/man/man1/install.1
rm -v /usr/share/man/man1/nproc.1
rm -v /usr/share/man/man1/du.1
rm -v /usr/share/man/man1/dirname.1
rm -v /usr/share/man/man1/nice.1
rm -v /usr/share/man/man1/cksum.1
rm -v /usr/share/man/man1/timeout.1
rm -v /usr/share/man/man1/sort.1
rm -v /usr/share/man/man1/cat.1
rm -v /usr/share/man/man1/hostid.1
rm -v /usr/share/man/man1/whoami.1
rm -v /usr/share/man/man1/tac.1
rm -v /usr/share/man/man1/cp.1
rm -v /usr/share/man/man1/pinky.1
rm -v /usr/share/man/man1/mktemp.1
rm -v /usr/share/man/man1/shred.1
rm -v /usr/share/man/man1/stat.1
rm -v /usr/share/man/man1/runcon.1
rm -v /usr/share/man/man1/md5sum.1
rm -v /usr/share/man/man1/rm.1
rm -v /usr/share/man/man1/ptx.1
rm -v /usr/share/man/man1/ls.1
rm -v /usr/share/man/man1/df.1
rm -v /usr/share/man/man1/echo.1
rm -v /usr/share/man/man1/who.1
rm -v /usr/share/man/man1/false.1
rm -v /usr/share/man/man1/chcon.1
rm -v /usr/share/man/man1/chmod.1
rm -v /usr/share/man/man1/fold.1
rm -v /usr/share/man/man1/rmdir.1
rm -v /usr/share/man/man1/mkfifo.1
rm -v /usr/share/man/man1/tty.1
rm -v /usr/share/man/man1/wc.1
rm -v /usr/share/man/man1/vdir.1
rm -v /usr/share/man/man1/unlink.1
rm -v /usr/share/man/man1/readlink.1
rm -v /usr/share/man/man1/uname.1
rm -v /usr/share/man/man1/users.1
rm -v /usr/share/man/man1/printenv.1
rm -v /usr/share/man/man1/date.1
rm -v /usr/share/man/man1/paste.1
rm -v /usr/share/man/man1/base64.1
rm -v /usr/share/man/man1/csplit.1
rm -v /usr/share/man/man1/cut.1
rm -v /usr/share/man/man1/fmt.1
rm -v /usr/share/man/man1/od.1
rm -v /usr/share/man/man1/tsort.1
rm -v /usr/share/man/man1/sha384sum.1
rm -v /usr/share/man/man1/link.1
rm -v /usr/share/man/man1/stdbuf.1
rm -v /usr/share/man/man1/factor.1
rm -v /usr/share/man/man1/dir.1
rm -v /usr/share/man/man1/expand.1
rm -v /usr/share/man/man1/id.1
rm -v /usr/share/man/man1/test.1
rm -v /usr/share/man/man1/dircolors.1
rm -v /usr/share/man/man1/mknod.1
rm -v /usr/share/man/man1/dd.1
rm -v /usr/share/man/man1/sha256sum.1
rm -v /usr/share/man/man1/expr.1
rm -v /usr/share/man/man1/nl.1
rm -v /usr/share/man/man1/tail.1
rm -v /usr/share/man/man1/yes.1
rm -v /usr/share/man/man1/pwd.1
rm -v /usr/share/man/man1/logname.1
rm -v /usr/share/man/man1/comm.1
rm -v /usr/share/man/man1/printf.1
rm -v /usr/share/man/man1/unexpand.1
rm -v /usr/share/man/man1/touch.1
rm -v /usr/share/man/man1/chgrp.1
rm -v /usr/share/man/man1/sha224sum.1
rm -v /usr/share/man/man1/truncate.1
rm -v /usr/share/man/man1/stty.1
rm -v /usr/share/man/man1/split.1
rm -v /usr/share/man/man1/head.1
rm -v /usr/share/man/man1/pathchk.1
rm -v /usr/share/man/man1/env.1
rm -v /usr/share/man/man1/uniq.1
rm -v /usr/share/man/man1/sum.1
rm -v /usr/share/man/man1/shuf.1
rm -v /usr/share/man/man1/pr.1
rm -v /usr/share/man/man1/join.1
rm -v /usr/share/man/man1/mv.1
rm -v /usr/share/man/man1/nohup.1
rm -v /usr/share/man/man1/groups.1
rm -v /usr/share/man/man1/basename.1
rm -v /usr/share/man/man1/chroot.1
rm -v /usr/share/man/man1/true.1
rm -v /usr/share/man/man1/chown.1
rm -v /usr/share/man/man1/sha1sum.1
rm -v /usr/share/man/man1/tee.1
rm -v /usr/share/man/man1/seq.1
rm -v /usr/share/locale/ko/LC_TIME/coreutils.mo
rm -v /usr/share/locale/ko/LC_MESSAGES/coreutils.mo
rm -v /usr/share/locale/ja/LC_TIME/coreutils.mo
rm -v /usr/share/locale/ja/LC_MESSAGES/coreutils.mo
rm -v /usr/share/locale/uk/LC_TIME/coreutils.mo
rm -v /usr/share/locale/uk/LC_MESSAGES/coreutils.mo
rm -v /usr/share/locale/ro/LC_TIME/coreutils.mo
rm -v /usr/share/locale/ro/LC_MESSAGES/coreutils.mo
rm -v /usr/share/locale/ru/LC_TIME/coreutils.mo
rm -v /usr/share/locale/ru/LC_MESSAGES/coreutils.mo
rm -v /usr/share/locale/es/LC_TIME/coreutils.mo
rm -v /usr/share/locale/es/LC_MESSAGES/coreutils.mo
rm -v /usr/share/locale/sv/LC_TIME/coreutils.mo
rm -v /usr/share/locale/sv/LC_MESSAGES/coreutils.mo
rm -v /usr/share/locale/nl/LC_TIME/coreutils.mo
rm -v /usr/share/locale/nl/LC_MESSAGES/coreutils.mo
rm -v /usr/share/locale/nb/LC_TIME/coreutils.mo
rm -v /usr/share/locale/nb/LC_MESSAGES/coreutils.mo
rm -v /usr/share/locale/vi/LC_TIME/coreutils.mo
rm -v /usr/share/locale/vi/LC_MESSAGES/coreutils.mo
rm -v /usr/share/locale/lg/LC_TIME/coreutils.mo
rm -v /usr/share/locale/lg/LC_MESSAGES/coreutils.mo
rm -v /usr/share/locale/et/LC_TIME/coreutils.mo
rm -v /usr/share/locale/et/LC_MESSAGES/coreutils.mo
rm -v /usr/share/locale/ca/LC_TIME/coreutils.mo
rm -v /usr/share/locale/ca/LC_MESSAGES/coreutils.mo
rm -v /usr/share/locale/tr/LC_TIME/coreutils.mo
rm -v /usr/share/locale/tr/LC_MESSAGES/coreutils.mo
rm -v /usr/share/locale/af/LC_TIME/coreutils.mo
rm -v /usr/share/locale/af/LC_MESSAGES/coreutils.mo
rm -v /usr/share/locale/gl/LC_TIME/coreutils.mo
rm -v /usr/share/locale/gl/LC_MESSAGES/coreutils.mo
rm -v /usr/share/locale/it/LC_TIME/coreutils.mo
rm -v /usr/share/locale/it/LC_MESSAGES/coreutils.mo
rm -v /usr/share/locale/sk/LC_TIME/coreutils.mo
rm -v /usr/share/locale/sk/LC_MESSAGES/coreutils.mo
rm -v /usr/share/locale/pl/LC_TIME/coreutils.mo
rm -v /usr/share/locale/pl/LC_MESSAGES/coreutils.mo
rm -v /usr/share/locale/ga/LC_TIME/coreutils.mo
rm -v /usr/share/locale/ga/LC_MESSAGES/coreutils.mo
rm -v /usr/share/locale/el/LC_TIME/coreutils.mo
rm -v /usr/share/locale/el/LC_MESSAGES/coreutils.mo
rm -v /usr/share/locale/eu/LC_TIME/coreutils.mo
rm -v /usr/share/locale/eu/LC_MESSAGES/coreutils.mo
rm -v /usr/share/locale/zh_TW/LC_TIME/coreutils.mo
rm -v /usr/share/locale/zh_TW/LC_MESSAGES/coreutils.mo
rm -v /usr/share/locale/hu/LC_TIME/coreutils.mo
rm -v /usr/share/locale/hu/LC_MESSAGES/coreutils.mo
rm -v /usr/share/locale/bg/LC_TIME/coreutils.mo
rm -v /usr/share/locale/bg/LC_MESSAGES/coreutils.mo
rm -v /usr/share/locale/fi/LC_TIME/coreutils.mo
rm -v /usr/share/locale/fi/LC_MESSAGES/coreutils.mo
rm -v /usr/share/locale/kk/LC_TIME/coreutils.mo
rm -v /usr/share/locale/kk/LC_MESSAGES/coreutils.mo
rm -v /usr/share/locale/de/LC_TIME/coreutils.mo
rm -v /usr/share/locale/de/LC_MESSAGES/coreutils.mo
rm -v /usr/share/locale/pt_BR/LC_TIME/coreutils.mo
rm -v /usr/share/locale/pt_BR/LC_MESSAGES/coreutils.mo
rm -v /usr/share/locale/id/LC_TIME/coreutils.mo
rm -v /usr/share/locale/id/LC_MESSAGES/coreutils.mo
rm -v /usr/share/locale/zh_CN/LC_TIME/coreutils.mo
rm -v /usr/share/locale/zh_CN/LC_MESSAGES/coreutils.mo
rm -v /usr/share/locale/be/LC_TIME/coreutils.mo
rm -v /usr/share/locale/be/LC_MESSAGES/coreutils.mo
rm -v /usr/share/locale/pt/LC_TIME/coreutils.mo
rm -v /usr/share/locale/pt/LC_MESSAGES/coreutils.mo
rm -v /usr/share/locale/sl/LC_TIME/coreutils.mo
rm -v /usr/share/locale/sl/LC_MESSAGES/coreutils.mo
rm -v /usr/share/locale/cs/LC_TIME/coreutils.mo
rm -v /usr/share/locale/cs/LC_MESSAGES/coreutils.mo
rm -v /usr/share/locale/fr/LC_TIME/coreutils.mo
rm -v /usr/share/locale/fr/LC_MESSAGES/coreutils.mo
rm -v /usr/share/locale/lt/LC_TIME/coreutils.mo
rm -v /usr/share/locale/lt/LC_MESSAGES/coreutils.mo
rm -v /usr/share/locale/da/LC_TIME/coreutils.mo
rm -v /usr/share/locale/da/LC_MESSAGES/coreutils.mo
rm -v /usr/share/locale/ms/LC_TIME/coreutils.mo
rm -v /usr/share/locale/ms/LC_MESSAGES/coreutils.mo
rm -rf -v /usr/lib/coreutils
