#!/bin/bash
rm -v ./sbin/tune2fs
rm -v ./sbin/mkfs.ext2
rm -v ./sbin/e2label
rm -v ./sbin/e2undo
rm -v ./sbin/mkfs.ext4
rm -v ./sbin/fsck.ext4dev
rm -v ./sbin/fsck.ext4
rm -v ./sbin/resize2fs
rm -v ./sbin/fsck.ext3
rm -v ./sbin/debugfs
rm -v ./sbin/fsck.ext2
rm -v ./sbin/logsave
rm -v ./sbin/mke2fs
rm -v ./sbin/mkfs.ext4dev
rm -v ./sbin/e2fsck
rm -v ./sbin/mkfs.ext3
rm -v ./sbin/e2image
rm -v ./sbin/dumpe2fs
rm -v ./sbin/badblocks
rm -v ./usr/sbin/filefrag
rm -v ./usr/sbin/mklost+found
rm -v ./usr/sbin/e2freefrag
rm -v ./usr/bin/lsattr
rm -v ./usr/bin/chattr
rm -v ./usr/share/info/libext2fs.info.gz
rm -v ./usr/share/man/man5/e2fsck.conf.5
rm -v ./usr/share/man/man5/mke2fs.conf.5
rm -v ./usr/share/man/man1/chattr.1
rm -v ./usr/share/man/man1/lsattr.1
rm -v ./usr/share/man/man8/mklost+found.8
rm -v ./usr/share/man/man8/e2undo.8
rm -v ./usr/share/man/man8/fsck.ext4.8
rm -v ./usr/share/man/man8/resize2fs.8
rm -v ./usr/share/man/man8/e2image.8
rm -v ./usr/share/man/man8/mkfs.ext3.8
rm -v ./usr/share/man/man8/e2fsck.8
rm -v ./usr/share/man/man8/debugfs.8
rm -v ./usr/share/man/man8/badblocks.8
rm -v ./usr/share/man/man8/mkfs.ext4dev.8
rm -v ./usr/share/man/man8/mke2fs.8
rm -v ./usr/share/man/man8/fsck.ext3.8
rm -v ./usr/share/man/man8/dumpe2fs.8
rm -v ./usr/share/man/man8/e2label.8
rm -v ./usr/share/man/man8/filefrag.8
rm -v ./usr/share/man/man8/e2freefrag.8
rm -v ./usr/share/man/man8/mkfs.ext2.8
rm -v ./usr/share/man/man8/mkfs.ext4.8
rm -v ./usr/share/man/man8/fsck.ext4dev.8
rm -v ./usr/share/man/man8/tune2fs.8
rm -v ./usr/share/man/man8/fsck.ext2.8
rm -v ./usr/share/man/man8/logsave.8
rm -v ./usr/share/locale/es/LC_MESSAGES/e2fsprogs.mo
rm -v ./usr/share/locale/sv/LC_MESSAGES/e2fsprogs.mo
rm -v ./usr/share/locale/nl/LC_MESSAGES/e2fsprogs.mo
rm -v ./usr/share/locale/vi/LC_MESSAGES/e2fsprogs.mo
rm -v ./usr/share/locale/ca/LC_MESSAGES/e2fsprogs.mo
rm -v ./usr/share/locale/tr/LC_MESSAGES/e2fsprogs.mo
rm -v ./usr/share/locale/it/LC_MESSAGES/e2fsprogs.mo
rm -v ./usr/share/locale/pl/LC_MESSAGES/e2fsprogs.mo
rm -v ./usr/share/locale/de/LC_MESSAGES/e2fsprogs.mo
rm -v ./usr/share/locale/id/LC_MESSAGES/e2fsprogs.mo
rm -v ./usr/share/locale/zh_CN/LC_MESSAGES/e2fsprogs.mo
rm -v ./usr/share/locale/cs/LC_MESSAGES/e2fsprogs.mo
rm -v ./usr/share/locale/fr/LC_MESSAGES/e2fsprogs.mo
rm -v ./usr/lib/libe2p.so
rm -v ./usr/lib/libss.so
rm -v ./usr/lib/e2initrd_helper
rm -v ./usr/lib/libext2fs.so
rm -v ./usr/lib/libcom_err.so
rm -v ./etc/mke2fs.conf
rm -v ./lib/libss.so.2
rm -v ./lib/libe2p.so.2
rm -v ./lib/libext2fs.so.2
rm -v ./lib/libe2p.so.2.3
rm -v ./lib/libcom_err.so.2
rm -v ./lib/libcom_err.so.2.1
rm -v ./lib/libext2fs.so.2.4
rm -v ./lib/libss.so.2.0
