#!/bin/bash
rm -v /usr/bin/find
rm -v /usr/bin/oldfind
rm -v /usr/bin/updatedb
rm -v /usr/bin/xargs
rm -v /usr/bin/locate
rm -v /usr/share/info/find-maint.info
rm -v /usr/share/info/find.info
rm -v /usr/share/man/man5/locatedb.5
rm -v /usr/share/man/man1/updatedb.1
rm -v /usr/share/man/man1/locate.1
rm -v /usr/share/man/man1/find.1
rm -v /usr/share/man/man1/xargs.1
rm -v /usr/share/locale/ko/LC_MESSAGES
rm -v /usr/share/locale/ko/LC_MESSAGES/findutils.mo
rm -v /usr/share/locale/sr/LC_MESSAGES/findutils.mo
rm -v /usr/share/locale/ja/LC_MESSAGES/findutils.mo
rm -v /usr/share/locale/rw/LC_MESSAGES/findutils.mo
rm -v /usr/share/locale/uk/LC_MESSAGES/findutils.mo
rm -v /usr/share/locale/ro/LC_MESSAGES/findutils.mo
rm -v /usr/share/locale/ru/LC_MESSAGES/findutils.mo
rm -v /usr/share/locale/es/LC_MESSAGES/findutils.mo
rm -v /usr/share/locale/sv/LC_MESSAGES/findutils.mo
rm -v /usr/share/locale/nl/LC_MESSAGES/findutils.mo
rm -v /usr/share/locale/vi/LC_MESSAGES/findutils.mo
rm -v /usr/share/locale/hr/LC_MESSAGES/findutils.mo
rm -v /usr/share/locale/lg/LC_MESSAGES/findutils.mo
rm -v /usr/share/locale/et/LC_MESSAGES/findutils.mo
rm -v /usr/share/locale/ca/LC_MESSAGES/findutils.mo
rm -v /usr/share/locale/tr/LC_MESSAGES/findutils.mo
rm -v /usr/share/locale/gl/LC_MESSAGES/findutils.mo
rm -v /usr/share/locale/it/LC_MESSAGES/findutils.mo
rm -v /usr/share/locale/eo/LC_MESSAGES/findutils.mo
rm -v /usr/share/locale/sk/LC_MESSAGES/findutils.mo
rm -v /usr/share/locale/pl/LC_MESSAGES/findutils.mo
rm -v /usr/share/locale/ga/LC_MESSAGES/findutils.mo
rm -v /usr/share/locale/el/LC_MESSAGES/findutils.mo
rm -v /usr/share/locale/zh_TW/LC_MESSAGES/findutils.mo
rm -v /usr/share/locale/hu/LC_MESSAGES/findutils.mo
rm -v /usr/share/locale/bg/LC_MESSAGES/findutils.mo
rm -v /usr/share/locale/fi/LC_MESSAGES/findutils.mo
rm -v /usr/share/locale/de/LC_MESSAGES/findutils.mo
rm -v /usr/share/locale/pt_BR/LC_MESSAGES/findutils.mo
rm -v /usr/share/locale/id/LC_MESSAGES/findutils.mo
rm -v /usr/share/locale/zh_CN/LC_MESSAGES/findutils.mo
rm -v /usr/share/locale/be/LC_MESSAGES/findutils.mo
rm -v /usr/share/locale/pt/LC_MESSAGES/findutils.mo
rm -v /usr/share/locale/sl/LC_MESSAGES/findutils.mo
rm -v /usr/share/locale/cs/LC_MESSAGES/findutils.mo
rm -v /usr/share/locale/fr/LC_MESSAGES/findutils.mo
rm -v /usr/share/locale/lt/LC_MESSAGES/findutils.mo
rm -v /usr/share/locale/da/LC_MESSAGES/findutils.mo
rm -v /usr/share/locale/ms/LC_MESSAGES/findutils.mo
rm -v /usr/lib/findutils
rm -v /usr/lib/findutils/code
rm -v /usr/lib/findutils/bigram
rm -v /usr/lib/findutils/frcode
rm -v /var/lib/locate
