#!/bin/bash
rm -v .
rm -v ./usr
rm -v ./usr/info
rm -v ./usr/info/dir
rm -v ./usr/info/flex.info-1
rm -v ./usr/info/flex.info
rm -v ./usr/info/flex.info-2
rm -v ./usr/man
rm -v ./usr/man/man1
rm -v ./usr/man/man1/flex.1
rm -v ./usr/bin
rm -v ./usr/bin/flex
rm -v ./usr/include
rm -v ./usr/include/FlexLexer.h
rm -v ./usr/share
rm -v ./usr/share/locale
rm -v ./usr/share/locale/ko
rm -v ./usr/share/locale/ko/LC_MESSAGES
rm -v ./usr/share/locale/ko/LC_MESSAGES/flex.mo
rm -v ./usr/share/locale/ro
rm -v ./usr/share/locale/ro/LC_MESSAGES
rm -v ./usr/share/locale/ro/LC_MESSAGES/flex.mo
rm -v ./usr/share/locale/ru
rm -v ./usr/share/locale/ru/LC_MESSAGES
rm -v ./usr/share/locale/ru/LC_MESSAGES/flex.mo
rm -v ./usr/share/locale/es
rm -v ./usr/share/locale/es/LC_MESSAGES
rm -v ./usr/share/locale/es/LC_MESSAGES/flex.mo
rm -v ./usr/share/locale/sv
rm -v ./usr/share/locale/sv/LC_MESSAGES
rm -v ./usr/share/locale/sv/LC_MESSAGES/flex.mo
rm -v ./usr/share/locale/nl
rm -v ./usr/share/locale/nl/LC_MESSAGES
rm -v ./usr/share/locale/nl/LC_MESSAGES/flex.mo
rm -v ./usr/share/locale/vi
rm -v ./usr/share/locale/vi/LC_MESSAGES
rm -v ./usr/share/locale/vi/LC_MESSAGES/flex.mo
rm -v ./usr/share/locale/ca
rm -v ./usr/share/locale/ca/LC_MESSAGES
rm -v ./usr/share/locale/ca/LC_MESSAGES/flex.mo
rm -v ./usr/share/locale/tr
rm -v ./usr/share/locale/tr/LC_MESSAGES
rm -v ./usr/share/locale/tr/LC_MESSAGES/flex.mo
rm -v ./usr/share/locale/pl
rm -v ./usr/share/locale/pl/LC_MESSAGES
rm -v ./usr/share/locale/pl/LC_MESSAGES/flex.mo
rm -v ./usr/share/locale/ga
rm -v ./usr/share/locale/ga/LC_MESSAGES
rm -v ./usr/share/locale/ga/LC_MESSAGES/flex.mo
rm -v ./usr/share/locale/de
rm -v ./usr/share/locale/de/LC_MESSAGES
rm -v ./usr/share/locale/de/LC_MESSAGES/flex.mo
rm -v ./usr/share/locale/pt_BR
rm -v ./usr/share/locale/pt_BR/LC_MESSAGES
rm -v ./usr/share/locale/pt_BR/LC_MESSAGES/flex.mo
rm -v ./usr/share/locale/zh_CN
rm -v ./usr/share/locale/zh_CN/LC_MESSAGES
rm -v ./usr/share/locale/zh_CN/LC_MESSAGES/flex.mo
rm -v ./usr/share/locale/fr
rm -v ./usr/share/locale/fr/LC_MESSAGES
rm -v ./usr/share/locale/fr/LC_MESSAGES/flex.mo
rm -v ./usr/share/locale/da
rm -v ./usr/share/locale/da/LC_MESSAGES
rm -v ./usr/share/locale/da/LC_MESSAGES/flex.mo
rm -v ./usr/lib
rm -v ./usr/lib/libfl_pic.a
rm -v ./usr/lib/libfl.a
