#!/bin/bash
rm -v ./usr/bin/gawk-3.1.8
rm -v ./usr/bin/awk
rm -v ./usr/bin/igawk
rm -v ./usr/bin/pgawk-3.1.8
rm -v ./usr/bin/gawk
rm -v ./usr/bin/pgawk
rm -rf -v ./usr/share/awk
rm -v ./usr/share/info/gawkinet.info
rm -v ./usr/share/info/gawk.info
rm -v ./usr/share/man/man1/gawk.1
rm -v ./usr/share/man/man1/igawk.1
rm -v ./usr/share/man/man1/pgawk.1
rm -v ./usr/share/locale/ja/LC_MESSAGES
rm -v ./usr/share/locale/ja/LC_MESSAGES/gawk.mo
rm -v ./usr/share/locale/rw/LC_MESSAGES/gawk.mo
rm -v ./usr/share/locale/ro/LC_MESSAGES/gawk.mo
rm -v ./usr/share/locale/es/LC_MESSAGES/gawk.mo
rm -v ./usr/share/locale/sv/LC_MESSAGES/gawk.mo
rm -v ./usr/share/locale/nl/LC_MESSAGES/gawk.mo
rm -v ./usr/share/locale/vi/LC_MESSAGES/gawk.mo
rm -v ./usr/share/locale/ca/LC_MESSAGES/gawk.mo
rm -v ./usr/share/locale/tr/LC_MESSAGES/gawk.mo
rm -v ./usr/share/locale/it/LC_MESSAGES/gawk.mo
rm -v ./usr/share/locale/pl/LC_MESSAGES/gawk.mo
rm -v ./usr/share/locale/ga/LC_MESSAGES/gawk.mo
rm -v ./usr/share/locale/he/LC_MESSAGES/gawk.mo
rm -v ./usr/share/locale/de/LC_MESSAGES/gawk.mo
rm -v ./usr/share/locale/pt_BR/LC_MESSAGES/gawk.mo
rm -v ./usr/share/locale/id/LC_MESSAGES/gawk.mo
rm -v ./usr/share/locale/zh_CN/LC_MESSAGES/gawk.mo
rm -v ./usr/share/locale/ast/LC_MESSAGES/gawk.mo
rm -v ./usr/share/locale/fr/LC_MESSAGES/gawk.mo
rm -v ./usr/share/locale/da/LC_MESSAGES/gawk.mo
rm -v ./usr/lib/awk/grcat
rm -v ./usr/lib/awk/pwcat
