#!/bin/bash

rm /usr/bin/g++
rm /usr/bin/i686-pc-linux-gnu-g++
rm /usr/bin/i686-pc-linux-gnu-gcc-4.5.2
rm /usr/bin/i686-pc-linux-gnu-c++
rm /usr/bin/c++
rm /usr/bin/cpp
rm /usr/bin/i686-pc-linux-gnu-gcc
rm /usr/bin/gcov
rm /usr/bin/gccbug
rm /usr/bin/gcc

rm -rf /usr/include/c++
rm -rf /usr/share/gcc-4.5.2
rm -rf /usr/lib/gcc

rm /usr/share/info/gccinstall.info
rm /usr/share/info/libgomp.info
rm /usr/share/info/cpp.info
rm /usr/share/info/gcc.info
rm /usr/share/info/cppinternals.info
rm /usr/share/info/gccint.info
rm /usr/share/man/man7/fsf-funding.7
rm /usr/share/man/man7/gfdl.7
rm /usr/share/man/man7/gpl.7
rm /usr/share/man/man1/g++.1
rm /usr/share/man/man1/cpp.1
rm /usr/share/man/man1/gcov.1
rm /usr/share/man/man1/gcc.1
rm /usr/share/locale/sr/LC_MESSAGES/gcc.mo
rm /usr/share/locale/ja/LC_MESSAGES/gcc.mo
rm /usr/share/locale/ja/LC_MESSAGES/cpplib.mo
rm /usr/share/locale/uk/LC_MESSAGES/cpplib.mo
rm /usr/share/locale/ru/LC_MESSAGES/gcc.mo
rm /usr/share/locale/es/LC_MESSAGES/gcc.mo
rm /usr/share/locale/es/LC_MESSAGES/cpplib.mo
rm /usr/share/locale/sv/LC_MESSAGES/gcc.mo
rm /usr/share/locale/sv/LC_MESSAGES/cpplib.mo
rm /usr/share/locale/nl/LC_MESSAGES/gcc.mo
rm /usr/share/locale/nl/LC_MESSAGES/cpplib.mo
rm /usr/share/locale/vi/LC_MESSAGES/gcc.mo
rm /usr/share/locale/vi/LC_MESSAGES/cpplib.mo
rm /usr/share/locale/ca/LC_MESSAGES/cpplib.mo
rm /usr/share/locale/tr/LC_MESSAGES/gcc.mo
rm /usr/share/locale/tr/LC_MESSAGES/cpplib.mo
rm /usr/share/locale/el/LC_MESSAGES/gcc.mo
rm /usr/share/locale/el/LC_MESSAGES/cpplib.mo
rm /usr/share/locale/zh_TW/LC_MESSAGES/gcc.mo
rm /usr/share/locale/zh_TW/LC_MESSAGES/cpplib.mo
rm /usr/share/locale/fi/LC_MESSAGES/gcc.mo
rm /usr/share/locale/fi/LC_MESSAGES/cpplib.mo
rm /usr/share/locale/de/LC_MESSAGES/libstdc++.mo
rm /usr/share/locale/de/LC_MESSAGES/gcc.mo
rm /usr/share/locale/de/LC_MESSAGES/cpplib.mo
rm /usr/share/locale/id/LC_MESSAGES/gcc.mo
rm /usr/share/locale/id/LC_MESSAGES/cpplib.mo
rm /usr/share/locale/zh_CN/LC_MESSAGES/gcc.mo
rm /usr/share/locale/zh_CN/LC_MESSAGES/cpplib.mo
rm /usr/share/locale/be/LC_MESSAGES/gcc.mo
rm /usr/share/locale/be/LC_MESSAGES/cpplib.mo
rm /usr/share/locale/fr/LC_MESSAGES/libstdc++.mo
rm /usr/share/locale/fr/LC_MESSAGES/gcc.mo
rm /usr/share/locale/fr/LC_MESSAGES/cpplib.mo
rm /usr/share/locale/da/LC_MESSAGES/gcc.mo
rm /usr/share/locale/da/LC_MESSAGES/cpplib.mo
rm /usr/lib/libgomp.a
rm /usr/lib/libgomp.la
rm /usr/lib/libmudflapth.la
rm /usr/lib/libssp_nonshared.a
rm /usr/lib/libmudflapth.a
rm /usr/lib/libsupc++.a
rm /usr/lib/libssp.la
rm /usr/lib/libmudflap.so
rm /usr/lib/libgomp.spec
rm /usr/lib/libstdc++.so.6.0.14-gdb.py
rm /usr/lib/libmudflap.so.0
rm /usr/lib/libstdc++.so.6.0.14
rm /usr/lib/libmudflapth.so.0.0.0
rm /usr/lib/libmudflapth.so
rm /usr/lib/libstdc++.la
rm /usr/lib/libgomp.so.1.0.0
rm /usr/lib/libssp_nonshared.la
rm /usr/lib/libssp.a
rm /usr/lib/libsupc++.la
rm /usr/lib/libstdc++.so
rm /usr/lib/libstdc++.a
rm /usr/lib/libstdc++.so.6
rm /usr/lib/libgcc_s.so
rm /usr/lib/libgomp.so.1
rm /usr/lib/libmudflapth.so.0
rm /usr/lib/libgomp.so
rm /usr/lib/libssp.so
rm /usr/lib/libmudflap.a
rm /usr/lib/libssp.so.0
rm /usr/lib/libgcc_s.so.1
rm /usr/lib/libmudflap.so.0.0.0
rm /usr/lib/libssp.so.0.0.0
rm /usr/lib/libmudflap.la