#!/bin/bash
rm -v ./usr/bin/msgconv
rm -v ./usr/bin/msgattrib
rm -v ./usr/bin/msgfmt
rm -v ./usr/bin/xgettext
rm -v ./usr/bin/gettext.sh
rm -v ./usr/bin/msgexec
rm -v ./usr/bin/ngettext
rm -v ./usr/bin/msgen
rm -v ./usr/bin/msgunfmt
rm -v ./usr/bin/msguniq
rm -v ./usr/bin/msgfilter
rm -v ./usr/bin/msginit
rm -v ./usr/bin/msggrep
rm -v ./usr/bin/msgmerge
rm -v ./usr/bin/msgcat
rm -v ./usr/bin/gettextize
rm -v ./usr/bin/gettext
rm -v ./usr/bin/recode-sr-latin
rm -v ./usr/bin/msgcmp
rm -v ./usr/bin/autopoint
rm -v ./usr/bin/envsubst
rm -v ./usr/bin/msgcomm
rm -v ./usr/include/autosprintf.h
rm -v ./usr/include/gettext-po.h
rm -v ./usr/share/info/autosprintf.info
rm -v ./usr/share/info/gettext.info
rm -v ./usr/share/man/man1/msgcmp.1
rm -v ./usr/share/man/man1/envsubst.1
rm -v ./usr/share/man/man1/msgfilter.1
rm -v ./usr/share/man/man1/msgen.1
rm -v ./usr/share/man/man1/msgunfmt.1
rm -v ./usr/share/man/man1/xgettext.1
rm -v ./usr/share/man/man1/msgattrib.1
rm -v ./usr/share/man/man1/ngettext.1
rm -v ./usr/share/man/man1/autopoint.1
rm -v ./usr/share/man/man1/msgcomm.1
rm -v ./usr/share/man/man1/msgmerge.1
rm -v ./usr/share/man/man1/gettextize.1
rm -v ./usr/share/man/man1/msgconv.1
rm -v ./usr/share/man/man1/msgcat.1
rm -v ./usr/share/man/man1/msginit.1
rm -v ./usr/share/man/man1/gettext.1
rm -v ./usr/share/man/man1/msgexec.1
rm -v ./usr/share/man/man1/msggrep.1
rm -v ./usr/share/man/man1/msgfmt.1
rm -v ./usr/share/man/man1/msguniq.1
rm -v ./usr/share/man/man1/recode-sr-latin.1
rm -v ./usr/share/man/man3/textdomain.3
rm -v ./usr/share/man/man3/dcngettext.3
rm -v ./usr/share/man/man3/dgettext.3
rm -v ./usr/share/man/man3/gettext.3
rm -v ./usr/share/man/man3/bindtextdomain.3
rm -v ./usr/share/man/man3/dcgettext.3
rm -v ./usr/share/man/man3/dngettext.3
rm -v ./usr/share/man/man3/bind_textdomain_codeset.3
rm -v ./usr/share/man/man3/ngettext.3
rm -v ./usr/share/aclocal/xsize.m4
rm -v ./usr/share/aclocal/stdint_h.m4
rm -v ./usr/share/aclocal/printf-posix.m4
rm -v ./usr/share/aclocal/fcntl-o.m4
rm -v ./usr/share/aclocal/visibility.m4
rm -v ./usr/share/aclocal/lib-ld.m4
rm -v ./usr/share/aclocal/size_max.m4
rm -v ./usr/share/aclocal/intl.m4
rm -v ./usr/share/aclocal/progtest.m4
rm -v ./usr/share/aclocal/iconv.m4
rm -v ./usr/share/aclocal/glibc21.m4
rm -v ./usr/share/aclocal/lcmessage.m4
rm -v ./usr/share/aclocal/lock.m4
rm -v ./usr/share/aclocal/inttypes-pri.m4
rm -v ./usr/share/aclocal/inttypes_h.m4
rm -v ./usr/share/aclocal/threadlib.m4
rm -v ./usr/share/aclocal/intldir.m4
rm -v ./usr/share/aclocal/wint_t.m4
rm -v ./usr/share/aclocal/gettext.m4
rm -v ./usr/share/aclocal/nls.m4
rm -v ./usr/share/aclocal/po.m4
rm -v ./usr/share/aclocal/lib-prefix.m4
rm -v ./usr/share/aclocal/wchar_t.m4
rm -v ./usr/share/aclocal/glibc2.m4
rm -v ./usr/share/aclocal/lib-link.m4
rm -v ./usr/share/aclocal/intdiv0.m4
rm -v ./usr/share/aclocal/intlmacosx.m4
rm -v ./usr/share/aclocal/longlong.m4
rm -v ./usr/share/aclocal/intmax.m4
rm -v ./usr/share/aclocal/codeset.m4
rm -v ./usr/share/aclocal/uintmax_t.m4
rm -rf -v ./usr/share/doc/gettext-0.18.1.1
rm -rf -v ./usr/share/gettext

rm -v ./usr/share/locale/en@quot/LC_MESSAGES
rm -v ./usr/share/locale/en@quot/LC_MESSAGES/gettext-tools.mo
rm -v ./usr/share/locale/en@quot/LC_MESSAGES/gettext-runtime.mo
rm -v ./usr/share/locale/ko/LC_MESSAGES/gettext-tools.mo
rm -v ./usr/share/locale/ko/LC_MESSAGES/gettext-runtime.mo
rm -v ./usr/share/locale/sr/LC_MESSAGES/gettext-tools.mo
rm -v ./usr/share/locale/sr/LC_MESSAGES/gettext-runtime.mo
rm -v ./usr/share/locale/ja/LC_MESSAGES/gettext-tools.mo
rm -v ./usr/share/locale/ja/LC_MESSAGES/gettext-runtime.mo
rm -v ./usr/share/locale/uk/LC_MESSAGES/gettext-tools.mo
rm -v ./usr/share/locale/uk/LC_MESSAGES/gettext-runtime.mo
rm -v ./usr/share/locale/ro/LC_MESSAGES/gettext-tools.mo
rm -v ./usr/share/locale/ro/LC_MESSAGES/gettext-runtime.mo
rm -v ./usr/share/locale/ru/LC_MESSAGES/gettext-tools.mo
rm -v ./usr/share/locale/ru/LC_MESSAGES/gettext-runtime.mo
rm -v ./usr/share/locale/es/LC_MESSAGES/gettext-tools.mo
rm -v ./usr/share/locale/es/LC_MESSAGES/gettext-runtime.mo
rm -v ./usr/share/locale/sv/LC_MESSAGES/gettext-tools.mo
rm -v ./usr/share/locale/sv/LC_MESSAGES/gettext-runtime.mo
rm -v ./usr/share/locale/nl/LC_MESSAGES/gettext-tools.mo
rm -v ./usr/share/locale/nl/LC_MESSAGES/gettext-runtime.mo
rm -v ./usr/share/locale/nb/LC_MESSAGES/gettext-tools.mo
rm -v ./usr/share/locale/nb/LC_MESSAGES/gettext-runtime.mo
rm -v ./usr/share/locale/vi/LC_MESSAGES/gettext-tools.mo
rm -v ./usr/share/locale/vi/LC_MESSAGES/gettext-runtime.mo
rm -v ./usr/share/locale/et/LC_MESSAGES/gettext-tools.mo
rm -v ./usr/share/locale/et/LC_MESSAGES/gettext-runtime.mo
rm -v ./usr/share/locale/ca/LC_MESSAGES/gettext-tools.mo
rm -v ./usr/share/locale/ca/LC_MESSAGES/gettext-runtime.mo
rm -v ./usr/share/locale/tr/LC_MESSAGES/gettext-tools.mo
rm -v ./usr/share/locale/tr/LC_MESSAGES/gettext-runtime.mo
rm -v ./usr/share/locale/gl/LC_MESSAGES/gettext-tools.mo
rm -v ./usr/share/locale/gl/LC_MESSAGES/gettext-runtime.mo
rm -v ./usr/share/locale/it/LC_MESSAGES/gettext-tools.mo
rm -v ./usr/share/locale/it/LC_MESSAGES/gettext-runtime.mo
rm -v ./usr/share/locale/eo/LC_MESSAGES/gettext-runtime.mo
rm -v ./usr/share/locale/sk/LC_MESSAGES/gettext-tools.mo
rm -v ./usr/share/locale/sk/LC_MESSAGES/gettext-runtime.mo
rm -v ./usr/share/locale/pl/LC_MESSAGES/gettext-tools.mo
rm -v ./usr/share/locale/pl/LC_MESSAGES/gettext-runtime.mo
rm -v ./usr/share/locale/ga/LC_MESSAGES/gettext-runtime.mo
rm -v ./usr/share/locale/el/LC_MESSAGES/gettext-tools.mo
rm -v ./usr/share/locale/el/LC_MESSAGES/gettext-runtime.mo
rm -v ./usr/share/locale/eu/LC_MESSAGES/gettext-tools.mo
rm -v ./usr/share/locale/en@boldquot/LC_MESSAGES/gettext-tools.mo
rm -v ./usr/share/locale/en@boldquot/LC_MESSAGES/gettext-runtime.mo
rm -v ./usr/share/locale/zh_TW/LC_MESSAGES/gettext-tools.mo
rm -v ./usr/share/locale/zh_TW/LC_MESSAGES/gettext-runtime.mo
rm -v ./usr/share/locale/nn/LC_MESSAGES/gettext-tools.mo
rm -v ./usr/share/locale/nn/LC_MESSAGES/gettext-runtime.mo
rm -v ./usr/share/locale/bg/LC_MESSAGES/gettext-tools.mo
rm -v ./usr/share/locale/bg/LC_MESSAGES/gettext-runtime.mo
rm -v ./usr/share/locale/fi/LC_MESSAGES/gettext-tools.mo
rm -v ./usr/share/locale/fi/LC_MESSAGES/gettext-runtime.mo
rm -v ./usr/share/locale/de/LC_MESSAGES/gettext-tools.mo
rm -v ./usr/share/locale/de/LC_MESSAGES/gettext-runtime.mo
rm -v ./usr/share/locale/pt_BR/LC_MESSAGES/gettext-tools.mo
rm -v ./usr/share/locale/pt_BR/LC_MESSAGES/gettext-runtime.mo
rm -v ./usr/share/locale/id/LC_MESSAGES/gettext-tools.mo
rm -v ./usr/share/locale/id/LC_MESSAGES/gettext-runtime.mo
rm -v ./usr/share/locale/zh_CN/LC_MESSAGES/gettext-tools.mo
rm -v ./usr/share/locale/zh_CN/LC_MESSAGES/gettext-runtime.mo
rm -v ./usr/share/locale/be/LC_MESSAGES/gettext-tools.mo
rm -v ./usr/share/locale/be/LC_MESSAGES/gettext-runtime.mo
rm -v ./usr/share/locale/pt/LC_MESSAGES/gettext-tools.mo
rm -v ./usr/share/locale/pt/LC_MESSAGES/gettext-runtime.mo
rm -v ./usr/share/locale/sl/LC_MESSAGES/gettext-tools.mo
rm -v ./usr/share/locale/sl/LC_MESSAGES/gettext-runtime.mo
rm -v ./usr/share/locale/cs/LC_MESSAGES/gettext-tools.mo
rm -v ./usr/share/locale/cs/LC_MESSAGES/gettext-runtime.mo
rm -v ./usr/share/locale/zh_HK/LC_MESSAGES/gettext-runtime.mo
rm -v ./usr/share/locale/fr/LC_MESSAGES/gettext-tools.mo
rm -v ./usr/share/locale/fr/LC_MESSAGES/gettext-runtime.mo
rm -v ./usr/share/locale/da/LC_MESSAGES/gettext-tools.mo
rm -v ./usr/share/locale/da/LC_MESSAGES/gettext-runtime.mo
rm -v ./usr/lib/libgettextpo.la
rm -v ./usr/lib/libgettextlib.la
rm -v ./usr/lib/libgettextpo.so.0
rm -v ./usr/lib/libgettextlib.so
rm -v ./usr/lib/libasprintf.so
rm -v ./usr/lib/libasprintf.so.0
rm -v ./usr/lib/libasprintf.la
rm -v ./usr/lib/libasprintf.so.0.0.0
rm -v ./usr/lib/libgettextlib-0.18.1.so
rm -v ./usr/lib/libgettextsrc.so
rm -rf -v ./usr/lib/gettext
rm -v ./usr/lib/libgettextpo.a
rm -v ./usr/lib/libgettextsrc.la
rm -v ./usr/lib/libgettextsrc-0.18.1.so
rm -v ./usr/lib/libgettextpo.so
rm -v ./usr/lib/libgettextpo.so.0.5.1
rm -v ./usr/lib/preloadable_libintl.so
rm -v ./usr/lib/libasprintf.a
