#!/bin/bash
rm -v /usr/share/info/gzip.info
rm -v /usr/share/man/man1/zcmp.1
rm -v /usr/share/man/man1/zcat.1
rm -v /usr/share/man/man1/znew.1
rm -v /usr/share/man/man1/zless.1
rm -v /usr/share/man/man1/gunzip.1
rm -v /usr/share/man/man1/zgrep.1
rm -v /usr/share/man/man1/gzip.1
rm -v /usr/share/man/man1/zmore.1
rm -v /usr/share/man/man1/zdiff.1
rm -v /usr/share/man/man1/zforce.1
rm -v /usr/share/man/man1/gzexe.1
rm -v /bin/zmore
rm -v /bin/gzip
rm -v /bin/zforce
rm -v /bin/zegrep
rm -v /bin/gunzip
rm -v /bin/uncompress
rm -v /bin/zfgrep
rm -v /bin/zcmp
rm -v /bin/zgrep
rm -v /bin/znew
rm -v /bin/zless
rm -v /bin/zdiff
rm -v /bin/zcat
rm -v /bin/gzexe
