#!/bin/bash
rm -v .
rm -v ./usr
rm -v ./usr/hputils
rm -v ./usr/hputils/hpdiags
rm -v ./usr/hputils/hpdiags/tcusb.err.xml
rm -v ./usr/hputils/hpdiags/pciboards.xml
rm -v ./usr/hputils/hpdiags/libtcvideo.so
rm -v ./usr/hputils/hpdiags/libtckeyboard.so
rm -v ./usr/hputils/hpdiags/tcmodem.err.xml
rm -v ./usr/hputils/hpdiags/libtcpci.so
rm -v ./usr/hputils/hpdiags/sg_scan
rm -v ./usr/hputils/hpdiags/test_components
rm -v ./usr/hputils/hpdiags/test_components/memory_Events.xml
rm -v ./usr/hputils/hpdiags/test_components/ilo_UserMessages.xml
rm -v ./usr/hputils/hpdiags/test_components/ilo_Events.xml
rm -v ./usr/hputils/hpdiags/test_components/mouse_Events.xml
rm -v ./usr/hputils/hpdiags/test_components/keyboard_UserMessages.xml
rm -v ./usr/hputils/hpdiags/test_components/mouse_UserMessages.xml
rm -v ./usr/hputils/hpdiags/test_components/cpu_Events.xml
rm -v ./usr/hputils/hpdiags/test_components/libstorage.so
rm -v ./usr/hputils/hpdiags/test_components/storage_Events.xml
rm -v ./usr/hputils/hpdiags/test_components/keyboard_Events.xml
rm -v ./usr/hputils/hpdiags/test_components/cpu_UserMessages.xml
rm -v ./usr/hputils/hpdiags/test_components/memory_UserMessages.xml
rm -v ./usr/hputils/hpdiags/test_components/storage_UserMessages.xml
rm -v ./usr/hputils/hpdiags/tcstorage.err.xml
rm -v ./usr/hputils/hpdiags/libtcaudio.so
rm -v ./usr/hputils/hpdiags/hpdiagstc
rm -v ./usr/hputils/hpdiags/libtcnetwork.so
rm -v ./usr/hputils/hpdiags/supportedsystems.dat
rm -v ./usr/hputils/hpdiags/v86d
rm -v ./usr/hputils/hpdiags/sysconf.dat
rm -v ./usr/hputils/hpdiags/libtcrib.so
rm -v ./usr/hputils/hpdiags/tcparallel.err.xml
rm -v ./usr/hputils/hpdiags/tccpu.err.xml
rm -v ./usr/hputils/hpdiags/pcivendors.txt
rm -v ./usr/hputils/hpdiags/tcstress.err.xml
rm -v ./usr/hputils/hpdiags/tcfirewire.err.xml
rm -v ./usr/hputils/hpdiags/en
rm -v ./usr/hputils/hpdiags/en/tcsysman.psGeneralFailure.htm
rm -v ./usr/hputils/hpdiags/en/tcsysman.psFanFailure.htm
rm -v ./usr/hputils/hpdiags/en/tcstorage.hddidentifydrive.htm
rm -v ./usr/hputils/hpdiags/en/tcstorage.hddpassamber.htm
rm -v ./usr/hputils/hpdiags/en/tcstorage.hddpass.htm
rm -v ./usr/hputils/hpdiags/en/tcsysman.psCommError.htm
rm -v ./usr/hputils/hpdiags/en/tcstorage.hddfail.htm
rm -v ./usr/hputils/hpdiags/en/tcsysman.psOverCurrent.htm
rm -v ./usr/hputils/hpdiags/en/tcsysman.psOverTemp.htm
rm -v ./usr/hputils/hpdiags/en/tcsysman.pspass.htm
rm -v ./usr/hputils/hpdiags/en/tcstorage.hddunknownamber.htm
rm -v ./usr/hputils/hpdiags/en/tcsysman.psOverVoltage.htm
rm -v ./usr/hputils/hpdiags/libmdacommon.so
rm -v ./usr/hputils/hpdiags/tcaudio.err.xml
rm -v ./usr/hputils/hpdiags/tcpci.err.xml
rm -v ./usr/hputils/hpdiags/hpdiags
rm -v ./usr/hputils/hpdiags/diagconfig.xml
rm -v ./usr/hputils/hpdiags/MemorySpareParts.xml
rm -v ./usr/hputils/hpdiags/tcsysman.err.xml
rm -v ./usr/hputils/hpdiags/libHBAAPI.so
rm -v ./usr/hputils/hpdiags/tcmouse.err.xml
rm -v ./usr/hputils/hpdiags/sdl.err.xml
rm -v ./usr/hputils/hpdiags/libtcparallel.so
rm -v ./usr/hputils/hpdiags/libtcstress.so
rm -v ./usr/hputils/hpdiags/hpdiagsai
rm -v ./usr/hputils/hpdiags/survey.xsl
rm -v ./usr/hputils/hpdiags/tones.wav
rm -v ./usr/hputils/hpdiags/pcichipsets.xml
rm -v ./usr/hputils/hpdiags/libtcrack.so
rm -v ./usr/hputils/hpdiags/libtcmouse.so
rm -v ./usr/hputils/hpdiags/libtcserial.so
rm -v ./usr/hputils/hpdiags/tcvideo.err.xml
rm -v ./usr/hputils/hpdiags/tcserial.err.xml
rm -v ./usr/hputils/hpdiags/tcrack.err.xml
rm -v ./usr/hputils/hpdiags/tcmemory.err.xml
rm -v ./usr/hputils/hpdiags/storagecontrollers.xml
rm -v ./usr/hputils/hpdiags/libbmapi_x64.so
rm -v ./usr/hputils/hpdiags/libtcmodem.so
rm -v ./usr/hputils/hpdiags/tcnetwork.err.xml
rm -v ./usr/hputils/hpdiags/libtccpu.so
rm -v ./usr/hputils/hpdiags/libtcmemory.so
rm -v ./usr/hputils/hpdiags/survey.dtd
rm -v ./usr/hputils/hpdiags/libtcusb.so
rm -v ./usr/hputils/hpdiags/libtcsysman.so
rm -v ./usr/hputils/hpdiags/libtcfirewire.so
rm -v ./usr/hputils/hpdiags/pcislotnumber
rm -v ./usr/hputils/hpdiags/pre_run_diags.sh
rm -v ./usr/hputils/hpdiags/tckeyboard.err.xml
rm -v ./usr/hputils/hpdiags/allboards.xml
rm -v ./usr/hputils/hpdiags/sg_map
rm -v ./usr/hputils/hpdiags/libtcstorage.so
rm -v ./usr/hputils/hpdiags/libtcinspect.so
rm -v ./usr/hputils/hpdiags/tcrib.err.xml
rm -v ./usr/hputils/hpdiags/tone.wav
rm -v ./usr/hputils/hpdiags/vmlhw.err.xml
