#!/bin/bash
rm -v /usr/bin/rcp
rm -v /usr/bin/rexec
rm -v /usr/bin/ifconfig
rm -v /usr/bin/tftp
rm -v /usr/bin/ftp
rm -v /usr/bin/traceroute
rm -v /usr/bin/talk
rm -v /usr/bin/telnet
rm -v /usr/bin/rlogin
rm -v /usr/bin/ping6
rm -v /usr/bin/rsh
rm -v /usr/bin/ping
rm -v /usr/bin/hostname
rm -v /usr/share/info/inetutils.info
rm -v /usr/share/man/man1/tftp.1
rm -v /usr/share/man/man1/ping6.1
rm -v /usr/share/man/man1/rsh.1
rm -v /usr/share/man/man1/hostname.1
rm -v /usr/share/man/man1/ftp.1
rm -v /usr/share/man/man1/rexec.1
rm -v /usr/share/man/man1/talk.1
rm -v /usr/share/man/man1/rcp.1
rm -v /usr/share/man/man1/telnet.1
rm -v /usr/share/man/man1/rlogin.1
rm -v /usr/share/man/man1/ping.1
rm -v /usr/share/man/man1/traceroute.1
rm -v /usr/share/man/man1/ifconfig.1
