#!/bin/bash
rm -v ./usr/bin/loadkeys
rm -v ./usr/bin/mapscrn
rm -v ./usr/bin/setmetamode
rm -v ./usr/bin/showconsolefont
rm -v ./usr/bin/chvt
rm -v ./usr/bin/deallocvt
rm -v ./usr/bin/setleds
rm -v ./usr/bin/fgconsole
rm -v ./usr/bin/psfgettable
rm -v ./usr/bin/kbdrate
rm -v ./usr/bin/resizecons
rm -v ./usr/bin/kbd_mode
rm -v ./usr/bin/dumpkeys
rm -v ./usr/bin/openvt
rm -v ./usr/bin/setkeycodes
rm -v ./usr/bin/psfxtable
rm -v ./usr/bin/setfont
rm -v ./usr/bin/getkeycodes
rm -v ./usr/bin/loadunimap
rm -v ./usr/bin/showkey
rm -v ./usr/bin/psfaddtable
rm -v ./usr/bin/psfstriptable
rm -v ./usr/bin/unicode_start
rm -v ./usr/bin/unicode_stop
rm -v ./usr/share/man/man5/keymaps.5
rm -v ./usr/share/man/man1/setmetamode.1
rm -v ./usr/share/man/man1/psfaddtable.1
rm -v ./usr/share/man/man1/loadkeys.1
rm -v ./usr/share/man/man1/chvt.1
rm -v ./usr/share/man/man1/setleds.1
rm -v ./usr/share/man/man1/openvt.1
rm -v ./usr/share/man/man1/psfgettable.1
rm -v ./usr/share/man/man1/dumpkeys.1
rm -v ./usr/share/man/man1/showkey.1
rm -v ./usr/share/man/man1/unicode_start.1
rm -v ./usr/share/man/man1/unicode_stop.1
rm -v ./usr/share/man/man1/psfstriptable.1
rm -v ./usr/share/man/man1/kbd_mode.1
rm -v ./usr/share/man/man1/deallocvt.1
rm -v ./usr/share/man/man1/fgconsole.1
rm -v ./usr/share/man/man1/psfxtable.1
rm -v ./usr/share/man/man8/setkeycodes.8
rm -v ./usr/share/man/man8/mapscrn.8
rm -v ./usr/share/man/man8/getkeycodes.8
rm -v ./usr/share/man/man8/kbdrate.8
rm -v ./usr/share/man/man8/resizecons.8
rm -v ./usr/share/man/man8/loadunimap.8
rm -v ./usr/share/man/man8/setfont.8
rm -v ./usr/share/man/man8/showconsolefont.8
rm -rf -v ./lib/kbd

