#!/bin/bash
rm -v ./usr/bin/make
rm -v ./usr/share/info/make.info-1
rm -v ./usr/share/info/make.info-2
rm -v ./usr/share/info/make.info
rm -v ./usr/share/man/man1/make.1
rm -v ./usr/share/locale/ko/LC_MESSAGES/make.mo
rm -v ./usr/share/locale/ja/LC_MESSAGES/make.mo
rm -v ./usr/share/locale/uk/LC_MESSAGES/make.mo
rm -v ./usr/share/locale/ru/LC_MESSAGES/make.mo
rm -v ./usr/share/locale/es/LC_MESSAGES/make.mo
rm -v ./usr/share/locale/sv/LC_MESSAGES/make.mo
rm -v ./usr/share/locale/nl/LC_MESSAGES/make.mo
rm -v ./usr/share/locale/vi/LC_MESSAGES/make.mo
rm -v ./usr/share/locale/hr/LC_MESSAGES/make.mo
rm -v ./usr/share/locale/tr/LC_MESSAGES/make.mo
rm -v ./usr/share/locale/gl/LC_MESSAGES/make.mo
rm -v ./usr/share/locale/it/LC_MESSAGES/make.mo
rm -v ./usr/share/locale/pl/LC_MESSAGES/make.mo
rm -v ./usr/share/locale/ga/LC_MESSAGES/make.mo
rm -v ./usr/share/locale/he/LC_MESSAGES/make.mo
rm -v ./usr/share/locale/fi/LC_MESSAGES/make.mo
rm -v ./usr/share/locale/de/LC_MESSAGES/make.mo
rm -v ./usr/share/locale/pt_BR/LC_MESSAGES/make.mo
rm -v ./usr/share/locale/id/LC_MESSAGES/make.mo
rm -v ./usr/share/locale/zh_CN/LC_MESSAGES/make.mo
rm -v ./usr/share/locale/be/LC_MESSAGES/make.mo
rm -v ./usr/share/locale/fr/LC_MESSAGES/make.mo
rm -v ./usr/share/locale/lt/LC_MESSAGES/make.mo
rm -v ./usr/share/locale/da/LC_MESSAGES/make.mo
