#!/bin/bash
rm -v ./usr/sbin/sshd
rm -v ./usr/bin/ssh
rm -v ./usr/bin/sftp
rm -v ./usr/bin/slogin
rm -v ./usr/bin/scp
rm -v ./usr/bin/ssh-keygen
rm -v ./usr/bin/ssh-add
rm -v ./usr/bin/ssh-keyscan
rm -v ./usr/bin/ssh-agent
rm -v ./usr/share/man/cat1
rm -v ./usr/share/man/cat1/ssh.1
rm -v ./usr/share/man/cat1/ssh-agent.1
rm -v ./usr/share/man/cat1/ssh-keygen.1
rm -v ./usr/share/man/cat1/slogin.1
rm -v ./usr/share/man/cat1/scp.1
rm -v ./usr/share/man/cat1/ssh-add.1
rm -v ./usr/share/man/cat1/sftp.1
rm -v ./usr/share/man/cat1/ssh-keyscan.1
rm -v ./usr/share/man/cat8/sshd.8
rm -v ./usr/share/man/cat8/ssh-pkcs11-helper.8
rm -v ./usr/share/man/cat8/ssh-keysign.8
rm -v ./usr/share/man/cat8/sftp-server.8
rm -v ./usr/share/man/cat5/ssh_config.5
rm -v ./usr/share/man/cat5/sshd_config.5
rm -v ./usr/share/man/cat5/moduli.5
rm -rf -v ./usr/lib/openssh
rm -v ./var/lib/sshd
rm -v ./etc/ssh/sshd_config
rm -v ./etc/ssh/moduli
rm -v ./etc/ssh/ssh_config
