#!/bin/bash
rm -v /sbin/sysctl
rm -v /usr/bin/snice
rm -v /usr/bin/skill
rm -v /usr/bin/slabtop
rm -v /usr/bin/watch
rm -v /usr/bin/top
rm -v /usr/bin/w
rm -v /usr/bin/pgrep
rm -v /usr/bin/uptime
rm -v /usr/bin/free
rm -v /usr/bin/pmap
rm -v /usr/bin/pkill
rm -v /usr/bin/vmstat
rm -v /usr/bin/tload
rm -v /usr/bin/pwdx
rm -v /usr/share/man/man5/sysctl.conf.5
rm -v /usr/share/man/man1/ps.1
rm -v /usr/share/man/man1/skill.1
rm -v /usr/share/man/man1/snice.1
rm -v /usr/share/man/man1/uptime.1
rm -v /usr/share/man/man1/w.1
rm -v /usr/share/man/man1/tload.1
rm -v /usr/share/man/man1/top.1
rm -v /usr/share/man/man1/kill.1
rm -v /usr/share/man/man1/pgrep.1
rm -v /usr/share/man/man1/watch.1
rm -v /usr/share/man/man1/pwdx.1
rm -v /usr/share/man/man1/slabtop.1
rm -v /usr/share/man/man1/free.1
rm -v /usr/share/man/man1/pmap.1
rm -v /usr/share/man/man1/pkill.1
rm -v /usr/share/man/man8/vmstat.8
rm -v /usr/share/man/man8/sysctl.8
rm -v /bin/kill
rm -v /bin/ps
rm -v /lib/libproc-3.2.8.so
