#!/bin/bash
rm -v .
rm -v ./usr
rm -v ./usr/lib
rm -v ./usr/lib/ruby
rm -v ./usr/lib/ruby/gems
rm -v ./usr/lib/ruby/gems/1.9.1
rm -v ./usr/lib/ruby/gems/1.9.1/gems
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/web
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/web/whatis
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/eventmachine.gemspec
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/ext
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/ext/cmain.cpp
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/ext/page.cpp
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/ext/sigs.o
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/ext/epoll.h
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/ext/cplusplus.cpp
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/ext/ssl.cpp
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/ext/em.o
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/ext/binder.cpp
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/ext/fastfilereader
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/ext/fastfilereader/mapper.o
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/ext/fastfilereader/rubymain.cpp
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/ext/fastfilereader/extconf.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/ext/fastfilereader/Makefile
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/ext/fastfilereader/mapper.h
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/ext/fastfilereader/mapper.cpp
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/ext/fastfilereader/fastfilereaderext.so
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/ext/fastfilereader/rubymain.o
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/ext/rubymain.cpp
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/ext/sigs.cpp
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/ext/extconf.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/ext/files.h
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/ext/rubyeventmachine.so
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/ext/pipe.cpp
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/ext/epoll.cpp
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/ext/emwin.o
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/ext/mkmf.log
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/ext/ssl.h
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/ext/epoll.o
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/ext/kb.cpp
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/ext/Makefile
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/ext/emwin.cpp
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/ext/ed.o
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/ext/kb.o
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/ext/emwin.h
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/ext/binder.o
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/ext/files.o
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/ext/ssl.o
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/ext/eventmachine_cpp.h
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/ext/binder.h
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/ext/ed.cpp
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/ext/page.o
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/ext/cmain.o
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/ext/eventmachine.h
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/ext/pipe.o
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/ext/em.cpp
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/ext/page.h
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/ext/ed.h
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/ext/files.cpp
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/ext/sigs.h
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/ext/project.h
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/ext/em.h
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/ext/rubymain.o
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/ext/cplusplus.o
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/README
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/setup.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/java
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/java/src
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/java/src/com
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/java/src/com/rubyeventmachine
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/java/src/com/rubyeventmachine/EmReactor.java
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/java/src/com/rubyeventmachine/EmReactorException.java
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/java/src/com/rubyeventmachine/application
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/java/src/com/rubyeventmachine/application/Application.java
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/java/src/com/rubyeventmachine/application/PeriodicTimer.java
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/java/src/com/rubyeventmachine/application/ConnectionFactory.java
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/java/src/com/rubyeventmachine/application/DefaultConnectionFactory.java
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/java/src/com/rubyeventmachine/application/Connection.java
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/java/src/com/rubyeventmachine/application/Timer.java
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/java/src/com/rubyeventmachine/EventableChannel.java
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/java/src/com/rubyeventmachine/EventableSocketChannel.java
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/java/src/com/rubyeventmachine/tests
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/java/src/com/rubyeventmachine/tests/ConnectTest.java
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/java/src/com/rubyeventmachine/tests/EMTest.java
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/java/src/com/rubyeventmachine/tests/ApplicationTest.java
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/java/src/com/rubyeventmachine/tests/TestTimers.java
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/java/src/com/rubyeventmachine/tests/TestServers.java
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/java/src/com/rubyeventmachine/tests/TestDatagrams.java
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/java/src/com/rubyeventmachine/EventableDatagramChannel.java
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/java/.classpath
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/java/.project
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/Rakefile
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/lib
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/lib/jeventmachine.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/lib/rubyeventmachine.so
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/lib/em
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/lib/em/protocols.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/lib/em/messages.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/lib/em/queue.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/lib/em/file_watch.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/lib/em/buftok.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/lib/em/process_watch.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/lib/em/spawnable.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/lib/em/channel.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/lib/em/callback.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/lib/em/processes.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/lib/em/version.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/lib/em/timers.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/lib/em/streamer.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/lib/em/protocols
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/lib/em/protocols/socks4.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/lib/em/protocols/object_protocol.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/lib/em/protocols/smtpserver.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/lib/em/protocols/tcptest.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/lib/em/protocols/stomp.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/lib/em/protocols/smtpclient.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/lib/em/protocols/saslauth.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/lib/em/protocols/header_and_content.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/lib/em/protocols/httpclient.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/lib/em/protocols/httpclient2.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/lib/em/protocols/linetext2.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/lib/em/protocols/line_and_text.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/lib/em/protocols/postgres3.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/lib/em/protocols/memcache.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/lib/em/future.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/lib/em/deferrable.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/lib/em/connection.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/lib/pr_eventmachine.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/lib/evma
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/lib/evma/callback.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/lib/evma/protocol.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/lib/evma/container.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/lib/evma/factory.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/lib/evma/reactor.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/lib/eventmachine.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/lib/evma.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/lib/fastfilereaderext.so
