#!/bin/bash
rm -v .
rm -v ./usr
rm -v ./usr/lib
rm -v ./usr/lib/ruby
rm -v ./usr/lib/ruby/gems
rm -v ./usr/lib/ruby/gems/1.9.1
rm -v ./usr/lib/ruby/gems/1.9.1/gems
rm -v ./usr/lib/ruby/gems/1.9.1/gems/mixlib-config-1.1.2
rm -v ./usr/lib/ruby/gems/1.9.1/gems/mixlib-config-1.1.2/features
rm -v ./usr/lib/ruby/gems/1.9.1/gems/mixlib-config-1.1.2/features/support
rm -v ./usr/lib/ruby/gems/1.9.1/gems/mixlib-config-1.1.2/features/support/env.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/mixlib-config-1.1.2/features/support/bobo.config
rm -v ./usr/lib/ruby/gems/1.9.1/gems/mixlib-config-1.1.2/features/support/config_it.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/mixlib-config-1.1.2/features/steps
rm -v ./usr/lib/ruby/gems/1.9.1/gems/mixlib-config-1.1.2/features/steps/config_steps.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/mixlib-config-1.1.2/features/mixlib_config.feature
rm -v ./usr/lib/ruby/gems/1.9.1/gems/mixlib-config-1.1.2/features/step_definitions
rm -v ./usr/lib/ruby/gems/1.9.1/gems/mixlib-config-1.1.2/features/step_definitions/mixlib_config_steps.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/mixlib-config-1.1.2/NOTICE
rm -v ./usr/lib/ruby/gems/1.9.1/gems/mixlib-config-1.1.2/README.rdoc
rm -v ./usr/lib/ruby/gems/1.9.1/gems/mixlib-config-1.1.2/VERSION.yml
rm -v ./usr/lib/ruby/gems/1.9.1/gems/mixlib-config-1.1.2/Rakefile
rm -v ./usr/lib/ruby/gems/1.9.1/gems/mixlib-config-1.1.2/LICENSE
rm -v ./usr/lib/ruby/gems/1.9.1/gems/mixlib-config-1.1.2/spec
rm -v ./usr/lib/ruby/gems/1.9.1/gems/mixlib-config-1.1.2/spec/spec_helper.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/mixlib-config-1.1.2/spec/mixlib
rm -v ./usr/lib/ruby/gems/1.9.1/gems/mixlib-config-1.1.2/spec/mixlib/config_spec.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/mixlib-config-1.1.2/spec/spec.opts
rm -v ./usr/lib/ruby/gems/1.9.1/gems/mixlib-config-1.1.2/lib
rm -v ./usr/lib/ruby/gems/1.9.1/gems/mixlib-config-1.1.2/lib/mixlib
rm -v ./usr/lib/ruby/gems/1.9.1/gems/mixlib-config-1.1.2/lib/mixlib/config.rb
