#!/bin/bash
rm -v .
rm -v ./usr
rm -v ./usr/lib
rm -v ./usr/lib/ruby
rm -v ./usr/lib/ruby/gems
rm -v ./usr/lib/ruby/gems/1.9.1
rm -v ./usr/lib/ruby/gems/1.9.1/gems
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/README.rdoc
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/bin
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/bin/ohai
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/Rakefile
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/LICENSE
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/system.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/mixin
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/mixin/ec2_metadata.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/mixin/command.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/mixin/from_file.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/mixin/string.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/log.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/application.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/config.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/version.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/exception.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/linux
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/linux/filesystem.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/linux/cpu.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/linux/ssh_host_key.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/linux/block_device.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/linux/lsb.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/linux/hostname.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/linux/platform.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/linux/uptime.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/linux/kernel.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/linux/virtualization.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/linux/ps.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/linux/network.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/linux/memory.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/ip_scopes.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/hpux
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/hpux/filesystem.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/hpux/cpu.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/hpux/ssh_host_key.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/hpux/hostname.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/hpux/platform.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/hpux/uptime.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/hpux/ps.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/hpux/network.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/hpux/memory.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/solaris2
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/solaris2/filesystem.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/solaris2/zpools.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/solaris2/cpu.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/solaris2/ssh_host_key.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/solaris2/hostname.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/solaris2/platform.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/solaris2/uptime.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/solaris2/kernel.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/solaris2/virtualization.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/solaris2/dmi.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/solaris2/ps.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/solaris2/network.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/chef.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/freebsd
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/freebsd/filesystem.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/freebsd/cpu.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/freebsd/ssh_host_key.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/freebsd/hostname.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/freebsd/platform.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/freebsd/uptime.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/freebsd/kernel.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/freebsd/virtualization.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/freebsd/ps.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/freebsd/network.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/freebsd/memory.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/ohai.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/cloud.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/ec2.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/java.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/perl.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/netbsd
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/netbsd/filesystem.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/netbsd/cpu.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/netbsd/ssh_host_key.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/netbsd/hostname.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/netbsd/platform.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/netbsd/uptime.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/netbsd/kernel.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/netbsd/virtualization.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/netbsd/ps.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/netbsd/network.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/netbsd/memory.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/erlang.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/keys.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/mono.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/darwin
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/darwin/filesystem.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/darwin/system_profiler.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/darwin/ssh_host_key.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/darwin/hostname.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/darwin/platform.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/darwin/uptime.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/darwin/kernel.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/darwin/ps.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/darwin/network.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/ruby.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/hostname.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/openbsd
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/openbsd/filesystem.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/openbsd/cpu.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/openbsd/ssh_host_key.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/openbsd/hostname.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/openbsd/platform.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/openbsd/uptime.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/openbsd/kernel.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/openbsd/virtualization.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/openbsd/ps.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/openbsd/network.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/openbsd/memory.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/lua.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/dmi_common.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/groovy.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/platform.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/uptime.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/kernel.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/passwd.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/languages.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/aix
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/aix/filesystem.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/aix/cpu.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/aix/ssh_host_key.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/aix/hostname.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/aix/platform.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/aix/uptime.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/aix/ps.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/aix/network.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/aix/memory.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/virtualization.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/command.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/windows
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/windows/filesystem.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/windows/cpu.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/windows/hostname.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/windows/platform.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/windows/kernel.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/windows/network.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/c.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/rackspace.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/dmi.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/python.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/network_listeners.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/os.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/php.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/sigar
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/sigar/filesystem.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/sigar/cpu.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/sigar/hostname.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/sigar/platform.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/sigar/uptime.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/sigar/network_route.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/sigar/network.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/sigar/memory.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/ohai_time.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/eucalyptus.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/plugins/network.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/ohai-0.6.10/lib/ohai/mash.rb
