#!/bin/bash
rm -v ./usr/share/info/sed.info
rm -v ./usr/share/man/man1/sed.1
rm -v ./usr/share/locale/ko/LC_MESSAGES/sed.mo
rm -v ./usr/share/locale/sr/LC_MESSAGES/sed.mo
rm -v ./usr/share/locale/ja/LC_MESSAGES/sed.mo
rm -v ./usr/share/locale/uk/LC_MESSAGES/sed.mo
rm -v ./usr/share/locale/ro/LC_MESSAGES/sed.mo
rm -v ./usr/share/locale/ru/LC_MESSAGES/sed.mo
rm -v ./usr/share/locale/es/LC_MESSAGES/sed.mo
rm -v ./usr/share/locale/sv/LC_MESSAGES/sed.mo
rm -v ./usr/share/locale/nl/LC_MESSAGES/sed.mo
rm -v ./usr/share/locale/vi/LC_MESSAGES/sed.mo
rm -v ./usr/share/locale/hr/LC_MESSAGES/sed.mo
rm -v ./usr/share/locale/et/LC_MESSAGES/sed.mo
rm -v ./usr/share/locale/ca/LC_MESSAGES/sed.mo
rm -v ./usr/share/locale/tr/LC_MESSAGES/sed.mo
rm -v ./usr/share/locale/af/LC_MESSAGES/sed.mo
rm -v ./usr/share/locale/gl/LC_MESSAGES/sed.mo
rm -v ./usr/share/locale/it/LC_MESSAGES/sed.mo
rm -v ./usr/share/locale/eo/LC_MESSAGES/sed.mo
rm -v ./usr/share/locale/sk/LC_MESSAGES/sed.mo
rm -v ./usr/share/locale/pl/LC_MESSAGES/sed.mo
rm -v ./usr/share/locale/ga/LC_MESSAGES/sed.mo
rm -v ./usr/share/locale/el/LC_MESSAGES/sed.mo
rm -v ./usr/share/locale/eu/LC_MESSAGES/sed.mo
rm -v ./usr/share/locale/zh_TW/LC_MESSAGES/sed.mo
rm -v ./usr/share/locale/he/LC_MESSAGES/sed.mo
rm -v ./usr/share/locale/hu/LC_MESSAGES/sed.mo
rm -v ./usr/share/locale/fi/LC_MESSAGES/sed.mo
rm -v ./usr/share/locale/de/LC_MESSAGES/sed.mo
rm -v ./usr/share/locale/pt_BR/LC_MESSAGES/sed.mo
rm -v ./usr/share/locale/id/LC_MESSAGES/sed.mo
rm -v ./usr/share/locale/zh_CN/LC_MESSAGES/sed.mo
rm -v ./usr/share/locale/pt/LC_MESSAGES/sed.mo
rm -v ./usr/share/locale/sl/LC_MESSAGES/sed.mo
rm -v ./usr/share/locale/cs/LC_MESSAGES/sed.mo
rm -v ./usr/share/locale/fr/LC_MESSAGES/sed.mo
rm -v ./usr/share/locale/da/LC_MESSAGES/sed.mo
rm -v ./bin/sed
