#!/bin/bash
rm -v /sbin/mkfs.cramfs
rm -v /sbin/ctrlaltdel
rm -v /sbin/swaplabel
rm -v /sbin/blkid
rm -v /sbin/fsck.minix
rm -v /sbin/mkfs
rm -v /sbin/fdisk
rm -v /sbin/fstrim
rm -v /sbin/findfs
rm -v /sbin/hwclock
rm -v /sbin/fsfreeze
rm -v /sbin/fsck
rm -v /sbin/swapon
rm -v /sbin/mkswap
rm -v /sbin/wipefs
rm -v /sbin/mkfs.bfs
rm -v /sbin/fsck.cramfs
rm -v /sbin/blockdev
rm -v /sbin/losetup
rm -v /sbin/sfdisk
rm -v /sbin/switch_root
rm -v /sbin/agetty
rm -v /sbin/pivot_root
rm -v /sbin/cfdisk
rm -v /sbin/mkfs.minix
rm -v /sbin/swapoff
rm -v /usr/sbin/rtcwake
rm -v /usr/sbin/uuidd
rm -v /usr/sbin/readprofile
rm -v /usr/sbin/fdformat
rm -v /usr/sbin/partx
rm -v /usr/sbin/addpart
rm -v /usr/sbin/tunelp
rm -v /usr/sbin/delpart
rm -v /usr/sbin/ldattach
rm -v /usr/bin/ipcmk
rm -v /usr/bin/rename
rm -v /usr/bin/hexdump
rm -v /usr/bin/ddate
rm -v /usr/bin/fallocate
rm -v /usr/bin/lscpu
rm -v /usr/bin/rev
rm -v /usr/bin/renice
rm -v /usr/bin/ipcs
rm -v /usr/bin/cal
rm -v /usr/bin/linux32
rm -v /usr/bin/look
rm -v /usr/bin/mcookie
rm -v /usr/bin/tailf
rm -v /usr/bin/setterm
rm -v /usr/bin/cytune
rm -v /usr/bin/line
rm -v /usr/bin/i386
rm -v /usr/bin/getopt
rm -v /usr/bin/script
rm -v /usr/bin/ionice
rm -v /usr/bin/chkdupexe
rm -v /usr/bin/ipcrm
rm -v /usr/bin/setarch
rm -v /usr/bin/logger
rm -v /usr/bin/ul
rm -v /usr/bin/linux64
rm -v /usr/bin/pg
rm -v /usr/bin/whereis
rm -v /usr/bin/namei
rm -v /usr/bin/chrt
rm -v /usr/bin/flock
rm -v /usr/bin/setsid
rm -v /usr/bin/scriptreplay
rm -v /usr/bin/write
rm -v /usr/bin/column
rm -v /usr/bin/taskset
rm -v /usr/bin/wall
rm -v /usr/bin/col
rm -v /usr/bin/uuidgen
rm -v /usr/bin/colcrt
rm -v /usr/bin/isosize
rm -v /usr/bin/colrm
rm -v /usr/bin/unshare
rm -v /usr/include
rm -v /usr/include/blkid
rm -v /usr/include/blkid/blkid.h
rm -v /usr/include/uuid
rm -v /usr/include/uuid/uuid.h
rm -v /usr/include/libmount
rm -v /usr/include/libmount/libmount.h
rm -v /usr/share/man/ru/man1/ddate.1
rm -v /usr/share/man/man5/fstab.5
rm -v /usr/share/man/man1/tailf.1
rm -v /usr/share/man/man1/hexdump.1
rm -v /usr/share/man/man1/ionice.1
rm -v /usr/share/man/man1/ipcrm.1
rm -v /usr/share/man/man1/column.1
rm -v /usr/share/man/man1/whereis.1
rm -v /usr/share/man/man1/logger.1
rm -v /usr/share/man/man1/fallocate.1
rm -v /usr/share/man/man1/write.1
rm -v /usr/share/man/man1/getopt.1
rm -v /usr/share/man/man1/pg.1
rm -v /usr/share/man/man1/ddate.1
rm -v /usr/share/man/man1/readprofile.1
rm -v /usr/share/man/man1/more.1
rm -v /usr/share/man/man1/lscpu.1
rm -v /usr/share/man/man1/setterm.1
rm -v /usr/share/man/man1/arch.1
rm -v /usr/share/man/man1/line.1
rm -v /usr/share/man/man1/chkdupexe.1
rm -v /usr/share/man/man1/mcookie.1
rm -v /usr/share/man/man1/namei.1
rm -v /usr/share/man/man1/chrt.1
rm -v /usr/share/man/man1/rename.1
rm -v /usr/share/man/man1/dmesg.1
rm -v /usr/share/man/man1/colcrt.1
rm -v /usr/share/man/man1/look.1
rm -v /usr/share/man/man1/uuidgen.1
rm -v /usr/share/man/man1/cal.1
rm -v /usr/share/man/man1/script.1
rm -v /usr/share/man/man1/col.1
rm -v /usr/share/man/man1/flock.1
rm -v /usr/share/man/man1/renice.1
rm -v /usr/share/man/man1/ul.1
rm -v /usr/share/man/man1/rev.1
rm -v /usr/share/man/man1/scriptreplay.1
rm -v /usr/share/man/man1/colrm.1
rm -v /usr/share/man/man1/ipcs.1
rm -v /usr/share/man/man1/wall.1
rm -v /usr/share/man/man1/taskset.1
rm -v /usr/share/man/man1/ipcmk.1
rm -v /usr/share/man/man1/setsid.1
rm -v /usr/share/man/man1/unshare.1
rm -v /usr/share/man/man8/swaplabel.8
rm -v /usr/share/man/man8/isosize.8
rm -v /usr/share/man/man8/mount.8
rm -v /usr/share/man/man8/ldattach.8
rm -v /usr/share/man/man8/linux64.8
rm -v /usr/share/man/man8/losetup.8
rm -v /usr/share/man/man8/mkswap.8
rm -v /usr/share/man/man8/fstrim.8
rm -v /usr/share/man/man8/agetty.8
rm -v /usr/share/man/man8/mkfs.bfs.8
rm -v /usr/share/man/man8/lsblk.8
rm -v /usr/share/man/man8/sfdisk.8
rm -v /usr/share/man/man8/findmnt.8
rm -v /usr/share/man/man8/umount.8
rm -v /usr/share/man/man8/fsck.8
rm -v /usr/share/man/man8/switch_root.8
rm -v /usr/share/man/man8/blockdev.8
rm -v /usr/share/man/man8/partx.8
rm -v /usr/share/man/man8/linux32.8
rm -v /usr/share/man/man8/tunelp.8
rm -v /usr/share/man/man8/i386.8
rm -v /usr/share/man/man8/uuidd.8
rm -v /usr/share/man/man8/hwclock.8
rm -v /usr/share/man/man8/blkid.8
rm -v /usr/share/man/man8/cfdisk.8
rm -v /usr/share/man/man8/swapoff.8
rm -v /usr/share/man/man8/setarch.8
rm -v /usr/share/man/man8/fdformat.8
rm -v /usr/share/man/man8/addpart.8
rm -v /usr/share/man/man8/mkfs.8
rm -v /usr/share/man/man8/mkfs.minix.8
rm -v /usr/share/man/man8/swapon.8
rm -v /usr/share/man/man8/fsck.minix.8
rm -v /usr/share/man/man8/ctrlaltdel.8
rm -v /usr/share/man/man8/fsfreeze.8
rm -v /usr/share/man/man8/rtcwake.8
rm -v /usr/share/man/man8/fdisk.8
rm -v /usr/share/man/man8/pivot_root.8
rm -v /usr/share/man/man8/delpart.8
rm -v /usr/share/man/man8/wipefs.8
rm -v /usr/share/man/man8/findfs.8
rm -v /usr/share/man/man8/cytune.8
rm -v /usr/share/man/man3/uuid_compare.3
rm -v /usr/share/man/man3/uuid_copy.3
rm -v /usr/share/man/man3/libblkid.3
rm -v /usr/share/man/man3/uuid_unparse.3
rm -v /usr/share/man/man3/uuid_parse.3
rm -v /usr/share/man/man3/uuid_clear.3
rm -v /usr/share/man/man3/uuid_time.3
rm -v /usr/share/man/man3/uuid_generate_random.3
rm -v /usr/share/man/man3/uuid_generate_time.3
rm -v /usr/share/man/man3/uuid.3
rm -v /usr/share/man/man3/uuid_generate.3
rm -v /usr/share/man/man3/uuid_is_null.3
rm -v /usr/share/getopt/getopt-parse.tcsh
rm -v /usr/share/getopt/getopt-parse.bash
rm -v /usr/share/getopt/getopt-test.bash
rm -v /usr/share/getopt/getopt-test.tcsh
rm -v /usr/share/locale/ja/LC_MESSAGES/util-linux.mo
rm -v /usr/share/locale/uk/LC_MESSAGES/util-linux.mo
rm -v /usr/share/locale/ru/LC_MESSAGES/util-linux.mo
rm -v /usr/share/locale/es/LC_MESSAGES/util-linux.mo
rm -v /usr/share/locale/sv/LC_MESSAGES/util-linux.mo
rm -v /usr/share/locale/nl/LC_MESSAGES/util-linux.mo
rm -v /usr/share/locale/vi/LC_MESSAGES/util-linux.mo
rm -v /usr/share/locale/et/LC_MESSAGES/util-linux.mo
rm -v /usr/share/locale/ca/LC_MESSAGES/util-linux.mo
rm -v /usr/share/locale/tr/LC_MESSAGES/util-linux.mo
rm -v /usr/share/locale/gl/LC_MESSAGES/util-linux.mo
rm -v /usr/share/locale/it/LC_MESSAGES/util-linux.mo
rm -v /usr/share/locale/pl/LC_MESSAGES/util-linux.mo
rm -v /usr/share/locale/eu/LC_MESSAGES/util-linux.mo
rm -v /usr/share/locale/zh_TW/LC_MESSAGES/util-linux.mo
rm -v /usr/share/locale/hu/LC_MESSAGES/util-linux.mo
rm -v /usr/share/locale/fi/LC_MESSAGES/util-linux.mo
rm -v /usr/share/locale/de/LC_MESSAGES/util-linux.mo
rm -v /usr/share/locale/pt_BR/LC_MESSAGES/util-linux.mo
rm -v /usr/share/locale/id/LC_MESSAGES/util-linux.mo
rm -v /usr/share/locale/zh_CN/LC_MESSAGES/util-linux.mo
rm -v /usr/share/locale/sl/LC_MESSAGES/util-linux.mo
rm -v /usr/share/locale/cs/LC_MESSAGES/util-linux.mo
rm -v /usr/share/locale/fr/LC_MESSAGES/util-linux.mo
rm -v /usr/share/locale/da/LC_MESSAGES/util-linux.mo
rm -v /usr/lib/libblkid.so
rm -v /usr/lib/libblkid.la
rm -v /usr/lib/libuuid.so
rm -v /usr/lib/libblkid.a
rm -v /usr/lib/libmount.so
rm -v /usr/lib/libuuid.la
rm -v /usr/lib/pkgconfig/mount.pc
rm -v /usr/lib/pkgconfig/uuid.pc
rm -v /usr/lib/pkgconfig/blkid.pc
rm -v /usr/lib/libuuid.a
rm -v /usr/lib/libmount.a
rm -v /usr/lib/libmount.la
rm -v /bin/dmesg
rm -v /bin/more
rm -v /bin/mount
rm -v /bin/arch
rm -v /bin/lsblk
rm -v /bin/findmnt
rm -v /bin/umount
rm -v /lib/libuuid.so.1
rm -v /lib/libblkid.so.1
rm -v /lib/libblkid.so.1.1.0
rm -v /lib/libmount.so.1
rm -v /lib/libuuid.so.1.3.0
rm -v /lib/libmount.so.1.1.0
