#!/bin/bash
rm -v /usr/bin/rview
rm -v /usr/bin/vimdiff
rm -v /usr/bin/rvim
rm -v /usr/bin/xxd
rm -v /usr/bin/view
rm -v /usr/bin/vimtutor
rm -v /usr/bin/ex
rm -v /usr/bin/vim
rm -v /usr/share/man/it.UTF-8/man1/view.1
rm -v /usr/share/man/it.UTF-8/man1/rview.1
rm -v /usr/share/man/it.UTF-8/man1/vimtutor.1
rm -v /usr/share/man/it.UTF-8/man1/evim.1
rm -v /usr/share/man/it.UTF-8/man1/xxd.1
rm -v /usr/share/man/it.UTF-8/man1/vim.1
rm -v /usr/share/man/it.UTF-8/man1/ex.1
rm -v /usr/share/man/it.UTF-8/man1/rvim.1
rm -v /usr/share/man/it.UTF-8/man1/vimdiff.1
rm -v /usr/share/man/ru.KOI8-R/man1/view.1
rm -v /usr/share/man/ru.KOI8-R/man1/rview.1
rm -v /usr/share/man/ru.KOI8-R/man1/vimtutor.1
rm -v /usr/share/man/ru.KOI8-R/man1/evim.1
rm -v /usr/share/man/ru.KOI8-R/man1/xxd.1
rm -v /usr/share/man/ru.KOI8-R/man1/vim.1
rm -v /usr/share/man/ru.KOI8-R/man1/ex.1
rm -v /usr/share/man/ru.KOI8-R/man1/rvim.1
rm -v /usr/share/man/ru.KOI8-R/man1/vimdiff.1
rm -v /usr/share/man/pl.UTF-8/man1/view.1
rm -v /usr/share/man/pl.UTF-8/man1/rview.1
rm -v /usr/share/man/pl.UTF-8/man1/vimtutor.1
rm -v /usr/share/man/pl.UTF-8/man1/evim.1
rm -v /usr/share/man/pl.UTF-8/man1/xxd.1
rm -v /usr/share/man/pl.UTF-8/man1/vim.1
rm -v /usr/share/man/pl.UTF-8/man1/ex.1
rm -v /usr/share/man/pl.UTF-8/man1/rvim.1
rm -v /usr/share/man/pl.UTF-8/man1/vimdiff.1
rm -v /usr/share/man/fr.UTF-8/man1/view.1
rm -v /usr/share/man/fr.UTF-8/man1/rview.1
rm -v /usr/share/man/fr.UTF-8/man1/vimtutor.1
rm -v /usr/share/man/fr.UTF-8/man1/evim.1
rm -v /usr/share/man/fr.UTF-8/man1/xxd.1
rm -v /usr/share/man/fr.UTF-8/man1/vim.1
rm -v /usr/share/man/fr.UTF-8/man1/ex.1
rm -v /usr/share/man/fr.UTF-8/man1/rvim.1
rm -v /usr/share/man/fr.UTF-8/man1/vimdiff.1
rm -v /usr/share/man/it/man1/view.1
rm -v /usr/share/man/it/man1/rview.1
rm -v /usr/share/man/it/man1/vimtutor.1
rm -v /usr/share/man/it/man1/evim.1
rm -v /usr/share/man/it/man1/xxd.1
rm -v /usr/share/man/it/man1/vim.1
rm -v /usr/share/man/it/man1/ex.1
rm -v /usr/share/man/it/man1/rvim.1
rm -v /usr/share/man/it/man1/vimdiff.1
rm -v /usr/share/man/pl/man1/view.1
rm -v /usr/share/man/pl/man1/rview.1
rm -v /usr/share/man/pl/man1/vimtutor.1
rm -v /usr/share/man/pl/man1/evim.1
rm -v /usr/share/man/pl/man1/xxd.1
rm -v /usr/share/man/pl/man1/vim.1
rm -v /usr/share/man/pl/man1/ex.1
rm -v /usr/share/man/pl/man1/rvim.1
rm -v /usr/share/man/pl/man1/vimdiff.1
rm -v /usr/share/man/fr.ISO8859-1/man1/view.1
rm -v /usr/share/man/fr.ISO8859-1/man1/rview.1
rm -v /usr/share/man/fr.ISO8859-1/man1/vimtutor.1
rm -v /usr/share/man/fr.ISO8859-1/man1/evim.1
rm -v /usr/share/man/fr.ISO8859-1/man1/xxd.1
rm -v /usr/share/man/fr.ISO8859-1/man1/vim.1
rm -v /usr/share/man/fr.ISO8859-1/man1/ex.1
rm -v /usr/share/man/fr.ISO8859-1/man1/rvim.1
rm -v /usr/share/man/fr.ISO8859-1/man1/vimdiff.1
rm -v /usr/share/man/man1/view.1
rm -v /usr/share/man/man1/rview.1
rm -v /usr/share/man/man1/vimtutor.1
rm -v /usr/share/man/man1/evim.1
rm -v /usr/share/man/man1/xxd.1
rm -v /usr/share/man/man1/vim.1
rm -v /usr/share/man/man1/ex.1
rm -v /usr/share/man/man1/rvim.1
rm -v /usr/share/man/man1/vimdiff.1
rm -v /usr/share/man/it.ISO8859-1/man1/view.1
rm -v /usr/share/man/it.ISO8859-1/man1/rview.1
rm -v /usr/share/man/it.ISO8859-1/man1/vimtutor.1
rm -v /usr/share/man/it.ISO8859-1/man1/evim.1
rm -v /usr/share/man/it.ISO8859-1/man1/xxd.1
rm -v /usr/share/man/it.ISO8859-1/man1/vim.1
rm -v /usr/share/man/it.ISO8859-1/man1/ex.1
rm -v /usr/share/man/it.ISO8859-1/man1/rvim.1
rm -v /usr/share/man/it.ISO8859-1/man1/vimdiff.1
rm -v /usr/share/man/ru.UTF-8/man1/view.1
rm -v /usr/share/man/ru.UTF-8/man1/rview.1
rm -v /usr/share/man/ru.UTF-8/man1/vimtutor.1
rm -v /usr/share/man/ru.UTF-8/man1/evim.1
rm -v /usr/share/man/ru.UTF-8/man1/xxd.1
rm -v /usr/share/man/ru.UTF-8/man1/vim.1
rm -v /usr/share/man/ru.UTF-8/man1/ex.1
rm -v /usr/share/man/ru.UTF-8/man1/rvim.1
rm -v /usr/share/man/ru.UTF-8/man1/vimdiff.1
rm -v /usr/share/man/pl.ISO8859-2/man1/view.1
rm -v /usr/share/man/pl.ISO8859-2/man1/rview.1
rm -v /usr/share/man/pl.ISO8859-2/man1/vimtutor.1
rm -v /usr/share/man/pl.ISO8859-2/man1/evim.1
rm -v /usr/share/man/pl.ISO8859-2/man1/xxd.1
rm -v /usr/share/man/pl.ISO8859-2/man1/vim.1
rm -v /usr/share/man/pl.ISO8859-2/man1/ex.1
rm -v /usr/share/man/pl.ISO8859-2/man1/rvim.1
rm -v /usr/share/man/pl.ISO8859-2/man1/vimdiff.1
rm -v /usr/share/man/fr/man1/view.1
rm -v /usr/share/man/fr/man1/rview.1
rm -v /usr/share/man/fr/man1/vimtutor.1
rm -v /usr/share/man/fr/man1/evim.1
rm -v /usr/share/man/fr/man1/xxd.1
rm -v /usr/share/man/fr/man1/vim.1
rm -v /usr/share/man/fr/man1/ex.1
rm -v /usr/share/man/fr/man1/rvim.1
rm -v /usr/share/man/fr/man1/vimdiff.1
rm -rf -v /usr/share/vim/vim73

