#!/bin/bash
rm -v /usr/bin/lzfgrep
rm -v /usr/bin/lzcat
rm -v /usr/bin/lzmadec
rm -v /usr/bin/xzegrep
rm -v /usr/bin/xzdiff
rm -v /usr/bin/xzcat
rm -v /usr/bin/lzegrep
rm -v /usr/bin/xzfgrep
rm -v /usr/bin/lzgrep
rm -v /usr/bin/unlzma
rm -v /usr/bin/lzma
rm -v /usr/bin/unxz
rm -v /usr/bin/lzmainfo
rm -v /usr/bin/xzdec
rm -v /usr/bin/xzless
rm -v /usr/bin/lzless
rm -v /usr/bin/xzcmp
rm -v /usr/bin/lzmore
rm -v /usr/bin/xzgrep
rm -v /usr/bin/xz
rm -v /usr/bin/lzdiff
rm -v /usr/bin/xzmore
rm -v /usr/bin/lzcmp
rm -v /usr/include/lzma.h
rm -v /usr/include/lzma
rm -v /usr/include/lzma/index.h
rm -v /usr/include/lzma/version.h
rm -v /usr/include/lzma/base.h
rm -v /usr/include/lzma/hardware.h
rm -v /usr/include/lzma/vli.h
rm -v /usr/include/lzma/bcj.h
rm -v /usr/include/lzma/container.h
rm -v /usr/include/lzma/check.h
rm -v /usr/include/lzma/index_hash.h
rm -v /usr/include/lzma/filter.h
rm -v /usr/include/lzma/lzma.h
rm -v /usr/include/lzma/block.h
rm -v /usr/include/lzma/stream_flags.h
rm -v /usr/include/lzma/delta.h
rm -v /usr/share/man/man1/lzdiff.1
rm -v /usr/share/man/man1/xzegrep.1
rm -v /usr/share/man/man1/xzcat.1
rm -v /usr/share/man/man1/lzma.1
rm -v /usr/share/man/man1/xzgrep.1
rm -v /usr/share/man/man1/lzless.1
rm -v /usr/share/man/man1/xzdiff.1
rm -v /usr/share/man/man1/lzmainfo.1
rm -v /usr/share/man/man1/xz.1
rm -v /usr/share/man/man1/lzmadec.1
rm -v /usr/share/man/man1/xzless.1
rm -v /usr/share/man/man1/lzmore.1
rm -v /usr/share/man/man1/unxz.1
rm -v /usr/share/man/man1/unlzma.1
rm -v /usr/share/man/man1/lzegrep.1
rm -v /usr/share/man/man1/lzcat.1
rm -v /usr/share/man/man1/lzfgrep.1
rm -v /usr/share/man/man1/xzcmp.1
rm -v /usr/share/man/man1/xzdec.1
rm -v /usr/share/man/man1/lzcmp.1
rm -v /usr/share/man/man1/lzgrep.1
rm -v /usr/share/man/man1/xzmore.1
rm -v /usr/share/man/man1/xzfgrep.1
rm -rf -v /usr/share/doc/xz-5.0.1
rm -v /usr/share/locale/it/LC_MESSAGES/xz.mo
rm -v /usr/share/locale/de/LC_MESSAGES/xz.mo
rm -v /usr/share/locale/cs/LC_MESSAGES/xz.mo
rm -v /usr/lib/liblzma.la
rm -v /usr/lib/liblzma.so
rm -v /usr/lib/liblzma.so.5.0.1
rm -v /usr/lib/liblzma.a
rm -v /usr/lib/pkgconfig/liblzma.pc
rm -v /usr/lib/liblzma.so.5
