#!/bin/bash
rm -v ./usr/lib/ruby/gems/1.9.1/gems/yajl-ruby-1.1.0
rm -v ./usr/lib/ruby/gems/1.9.1/gems/yajl-ruby-1.1.0/ext
rm -v ./usr/lib/ruby/gems/1.9.1/gems/yajl-ruby-1.1.0/ext/yajl
rm -v ./usr/lib/ruby/gems/1.9.1/gems/yajl-ruby-1.1.0/ext/yajl/yajl_encode.h
rm -v ./usr/lib/ruby/gems/1.9.1/gems/yajl-ruby-1.1.0/ext/yajl/yajl_parser.o
rm -v ./usr/lib/ruby/gems/1.9.1/gems/yajl-ruby-1.1.0/ext/yajl/yajl_encode.o
rm -v ./usr/lib/ruby/gems/1.9.1/gems/yajl-ruby-1.1.0/ext/yajl/extconf.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/yajl-ruby-1.1.0/ext/yajl/yajl_ext.h
rm -v ./usr/lib/ruby/gems/1.9.1/gems/yajl-ruby-1.1.0/ext/yajl/yajl_version.o
rm -v ./usr/lib/ruby/gems/1.9.1/gems/yajl-ruby-1.1.0/ext/yajl/yajl_lex.c
rm -v ./usr/lib/ruby/gems/1.9.1/gems/yajl-ruby-1.1.0/ext/yajl/yajl_alloc.h
rm -v ./usr/lib/ruby/gems/1.9.1/gems/yajl-ruby-1.1.0/ext/yajl/yajl_ext.o
rm -v ./usr/lib/ruby/gems/1.9.1/gems/yajl-ruby-1.1.0/ext/yajl/yajl_alloc.c
rm -v ./usr/lib/ruby/gems/1.9.1/gems/yajl-ruby-1.1.0/ext/yajl/yajl_buf.h
rm -v ./usr/lib/ruby/gems/1.9.1/gems/yajl-ruby-1.1.0/ext/yajl/yajl_bytestack.h
rm -v ./usr/lib/ruby/gems/1.9.1/gems/yajl-ruby-1.1.0/ext/yajl/yajl_buf.c
rm -v ./usr/lib/ruby/gems/1.9.1/gems/yajl-ruby-1.1.0/ext/yajl/Makefile
rm -v ./usr/lib/ruby/gems/1.9.1/gems/yajl-ruby-1.1.0/ext/yajl/yajl_parser.c
rm -v ./usr/lib/ruby/gems/1.9.1/gems/yajl-ruby-1.1.0/ext/yajl/yajl_gen.c
rm -v ./usr/lib/ruby/gems/1.9.1/gems/yajl-ruby-1.1.0/ext/yajl/yajl_lex.o
rm -v ./usr/lib/ruby/gems/1.9.1/gems/yajl-ruby-1.1.0/ext/yajl/yajl.c
rm -v ./usr/lib/ruby/gems/1.9.1/gems/yajl-ruby-1.1.0/ext/yajl/yajl_encode.c
rm -v ./usr/lib/ruby/gems/1.9.1/gems/yajl-ruby-1.1.0/ext/yajl/yajl_ext.c
rm -v ./usr/lib/ruby/gems/1.9.1/gems/yajl-ruby-1.1.0/ext/yajl/yajl_buf.o
rm -v ./usr/lib/ruby/gems/1.9.1/gems/yajl-ruby-1.1.0/ext/yajl/api
rm -v ./usr/lib/ruby/gems/1.9.1/gems/yajl-ruby-1.1.0/ext/yajl/api/yajl_gen.h
rm -v ./usr/lib/ruby/gems/1.9.1/gems/yajl-ruby-1.1.0/ext/yajl/api/yajl_common.h
rm -v ./usr/lib/ruby/gems/1.9.1/gems/yajl-ruby-1.1.0/ext/yajl/api/yajl_version.h
rm -v ./usr/lib/ruby/gems/1.9.1/gems/yajl-ruby-1.1.0/ext/yajl/api/yajl_parse.h
rm -v ./usr/lib/ruby/gems/1.9.1/gems/yajl-ruby-1.1.0/ext/yajl/yajl_gen.o
rm -v ./usr/lib/ruby/gems/1.9.1/gems/yajl-ruby-1.1.0/ext/yajl/yajl_lex.h
rm -v ./usr/lib/ruby/gems/1.9.1/gems/yajl-ruby-1.1.0/ext/yajl/yajl_parser.h
rm -v ./usr/lib/ruby/gems/1.9.1/gems/yajl-ruby-1.1.0/ext/yajl/yajl_version.c
rm -v ./usr/lib/ruby/gems/1.9.1/gems/yajl-ruby-1.1.0/ext/yajl/yajl_alloc.o
rm -v ./usr/lib/ruby/gems/1.9.1/gems/yajl-ruby-1.1.0/ext/yajl/yajl.o
rm -v ./usr/lib/ruby/gems/1.9.1/gems/yajl-ruby-1.1.0/ext/yajl/yajl.so
rm -v ./usr/lib/ruby/gems/1.9.1/gems/yajl-ruby-1.1.0/MIT-LICENSE
rm -v ./usr/lib/ruby/gems/1.9.1/gems/yajl-ruby-1.1.0/Gemfile
rm -v ./usr/lib/ruby/gems/1.9.1/gems/yajl-ruby-1.1.0/yajl-ruby.gemspec
rm -v ./usr/lib/ruby/gems/1.9.1/gems/yajl-ruby-1.1.0/Rakefile
rm -v ./usr/lib/ruby/gems/1.9.1/gems/yajl-ruby-1.1.0/CHANGELOG.md
rm -v ./usr/lib/ruby/gems/1.9.1/gems/yajl-ruby-1.1.0/README.md
rm -v ./usr/lib/ruby/gems/1.9.1/gems/yajl-ruby-1.1.0/lib
rm -v ./usr/lib/ruby/gems/1.9.1/gems/yajl-ruby-1.1.0/lib/yajl
rm -v ./usr/lib/ruby/gems/1.9.1/gems/yajl-ruby-1.1.0/lib/yajl/gzip
rm -v ./usr/lib/ruby/gems/1.9.1/gems/yajl-ruby-1.1.0/lib/yajl/gzip/stream_writer.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/yajl-ruby-1.1.0/lib/yajl/gzip/stream_reader.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/yajl-ruby-1.1.0/lib/yajl/gzip.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/yajl-ruby-1.1.0/lib/yajl/json_gem
rm -v ./usr/lib/ruby/gems/1.9.1/gems/yajl-ruby-1.1.0/lib/yajl/json_gem/encoding.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/yajl-ruby-1.1.0/lib/yajl/json_gem/parsing.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/yajl-ruby-1.1.0/lib/yajl/json_gem.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/yajl-ruby-1.1.0/lib/yajl/http_stream.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/yajl-ruby-1.1.0/lib/yajl/bzip2
rm -v ./usr/lib/ruby/gems/1.9.1/gems/yajl-ruby-1.1.0/lib/yajl/bzip2/stream_writer.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/yajl-ruby-1.1.0/lib/yajl/bzip2/stream_reader.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/yajl-ruby-1.1.0/lib/yajl/version.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/yajl-ruby-1.1.0/lib/yajl/deflate.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/yajl-ruby-1.1.0/lib/yajl/deflate
rm -v ./usr/lib/ruby/gems/1.9.1/gems/yajl-ruby-1.1.0/lib/yajl/deflate/stream_writer.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/yajl-ruby-1.1.0/lib/yajl/deflate/stream_reader.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/yajl-ruby-1.1.0/lib/yajl/bzip2.rb
rm -v ./usr/lib/ruby/gems/1.9.1/gems/yajl-ruby-1.1.0/lib/yajl/yajl.so
rm -v ./usr/lib/ruby/gems/1.9.1/gems/yajl-ruby-1.1.0/lib/yajl.rb
